### ISSUE TITLE
How can I render 3D charts?

### ISSUE THREAD

**Issue by TomasZorvan** [gevgeny/angular2-highcharts#1]
Hello,

can you help me on how can I render 3D charts with this library?
When I put 3D options in this.options it renders chart correctly but not in 3D.

Thanks

**Comment by gevgeny** [comment]
You need to load appropriate Highcharts module. Here is an example
http://plnkr.co/edit/4Eifda2IPpCjykONSQQJ?p=preview.
Here is more details about loading Highcharts modules http://www.highcharts.com/docs/getting-started/install-from-npm

**Comment by gevgeny** [comment]
Thanks for the question! I added appropriate section to the readme.

**Comment by TomasZorvan** [comment]
Thank you very much. Works as a charm ;)
