### ISSUE TITLE
Highstock on angular cli

### ISSUE THREAD

**Issue by koralu** [gevgeny/angular2-highcharts#101]
I try to implement highstock in angular cli but it seems it doesn't work. The simple charts works fine but with highstock I get the error-  "StockChart is unknown chart type"

**app.commponent.ts**
`import { Component } from '@angular/core';
import {Jsonp} from '@angular/http';

@Component({
  selector: 'app-root',
    styles: [`
      chart {
        display: block;
      }
    `],
    template: `<chart type="StockChart" [options]="options"></chart>`
})
export class AppComponent {
    constructor(jsonp : Jsonp) {
        jsonp.request('https://www.highcharts.com/samples/data/jsonp.php?filename=aapl-c.json&callback=JSONP_CALLBACK').subscribe(res => {
            this.options = {
                title : { text : 'AAPL Stock Price' },
                series : [{
                    name : 'AAPL',
                    data : res.json(),
                    tooltip: {
                        valueDecimals: 2
                    }
                }]
            };
        });
    }
    options: Object;
}`

**app.module.ts**
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule,Jsonp,JsonpModule } from '@angular/http';
import { ChartModule } from 'angular2-highcharts';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ChartModule,
    JsonpModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**Comment by gevgeny** [comment]
Looks like you plug `highcharts.js` rather than `highstock.js`. Look at the configs in example apps https://github.com/gevgeny/angular2-highcharts#installation

**Comment by unaor** [comment]
I have a similar issue, i need to plug the highcharts-more.js to use the solidgauge, but im not able so far

**Comment by gevgeny** [comment]
@unaor did you try as it is done in the installation examples ?

**Comment by aavernon2** [comment]
@koralu Did get highstock.js plugged?

**Comment by unaor** [comment]
hi @gevgeny  i tried doing the following in my component TS (its important to state that normal graphs are working fine, im having issues with solid gauge)
import {Highcharts} from 'angular2-highcharts';
import \* as HighChartsMore from 'highcharts/highcharts-more';
but im getting :'Cannot find module 'highcharts/highcharts-more'.
I've installed the following
"angular2-highcharts": "^0.3.5"
and later
"highcharts": "^5.0.2"

and im using the angular2 cli

**Comment by gevgeny** [comment]
i have not use angular2 CLI. So only thing i can help you with is direct webpack or systemjs config. Which was mentioned in my first comment.

**Comment by koralu** [comment]
I have found a solution, is not a very elegant one but it worked.

Change in ../node_module/highcharts/package.json 

> "main": "highcharts.js" -> "main": "highstock.js"

**Comment by gevgeny** [comment]
@koralu this is hacky and non supportable solution. I still don't understand what was the problem with my examples

**Comment by koralu** [comment]
From my point of view your examples are by far perfect (for direct webpack or systemjs). But in angular2 CLI importing extra module like in your example didn't work.

Probably because me and the others who have tried we are still confused about angular2 CLI importing library and stuff.

**Comment by gevgeny** [comment]
Hm. Thanks for the information. Will try angular2 cli later.

**Comment by unaor** [comment]
@gevgeny much appreciated

**Comment by zawars** [comment]
@gevgeny Have you tried with Angular CLI yet?

I am working on Angular CLI. I am facing difficulties doing this. Please help

**Comment by gevgeny** [comment]
not yet, sorry

**Comment by zawars** [comment]
@gevgeny That's fine. I've done it. :)

**Comment by gevgeny** [comment]
would be grate if you share it )

**Comment by zawars** [comment]
Sure, I would love to contribute. :)

**Comment by zawars** [comment]
---

## Solution for Angular CLI 

---

## chart.component.ts

```
import {Component, OnInit} from '@angular/core';
import {ChartModule} from "angular2-highcharts"

@Component({
  selector: 'app-chart',
  templateUrl: './chart.component.html',
  styleUrls: ['./chart.component.css']
})
export class ChartComponent implements OnInit {
  options: Object;
  constructor() {
    this.options = {
      chart: {
        zoomType: 'x',
        type: "spline"
      },
      title: {
        text: "Sample Chart"
      },
      subtitle: {
        text: "Trends"
      },
      xAxis: {
        title: {
          text: "Time Series"
        }
      },
      series: [{
        name: "Data Stream",
        data: [29.9, 71.5, 106.4, 129, 15, 6, 61, 5, 4, 16, 4, 1, 5, 48, 51, 5,
          13, 1, 1, 168, 15, 16, 1, 15, 18, 1, 51, 6, 10, 165, 61, 84, 94, 94,
          8, 98, 40, 15, 18, 46, 44, 65, 46, 6, 94, 64, 64, 86, 6, 40, 44, 56],
      }],
      exporting: {
        enabled: true
      },
      legend: {
        align: "right",
        verticalAlign: "middle",
        layout: "vertical",
        borderWidths: 10
      },
      tooltip: {
        split: "true"
      },
      plotOptions: {
        series: {
          compare: 'percent',
          showInNavigator: true
        }
      },
      rangeSelector: {
        enabled: true,
        allButtonsEnabled: true,
        buttons: [{
          type: 'hour',
          count: 1,
          text: '1h'
        }, {
          type: 'day',
          count: 1,
          text: '1d'
        }, {
          type: 'month',
          count: 1,
          text: '1m'
        }, {
          type: 'year',
          count: 1,
          text: '1y'
        }, {
          type: 'all',
          text: 'All'
        }],
        inputEnabled: true, // it supports only days
        //selected: 4 // all
      },
      navigator: {
        enabled: "true"
      },
    };
  }
  ngOnInit() {
  }
}
```

---

## chart.component.html

```
<chart  [options]="options" id="chart"></chart>
```

**Comment by unaor** [comment]
@zawars i think you didnt clarify the important part which is how to load the missing module (highcharts-more), what is written here is the normal usage of highcharts

**Comment by derailed** [comment]
Can someone post an actual working example? This is taking me way too long to figure out how this should work out of the box. I need a working example of using the latest ng2 with angularcli and loading solidgauge charts. The examples in this repo reference comp directives which are now long gone. Please update!!

**Comment by unaor** [comment]
i still have issues....

**Comment by vcward** [comment]
I'm also having the same problem with the StockChart type in an Angular-CLI project.
Not sure if this is a desirable solution, but editing the dist/HighchartsWrapper.js did the trick for now. (Changed the require('highcharts') back to require('highcharts/highstock.src'): 

```
"use strict";
var Highcharts = require('highcharts/highstock.src');
exports.Highcharts = Highcharts;
//# sourceMappingURL=HighchartsWrapper.js.map
```

**Comment by arjenbrandenburgh** [comment]
Not sure why this issue is closed. It still persist on the latest angular-cli (1.0.0-beta.20-4). Currently still on angular2-highcharts 0.3.4 since the 0.4.1 breaks the charts with the following error:

inline template:121:7 caused by: StockChart is unknown chart type

The examples provided don't work on angular-cli. Don't really see how the solution of @zawars solves anything. Think he just removed the "type" from the chart-tag and the angular2-highcharts is falling back to a regular chart which happens to work with his config.

**Comment by cedricleroy** [comment]
Anybody found an elegant way to solve this?

**Comment by tsvetkovv** [comment]
Guys, I've been trying fix it all day.
I've solved by adding [this alias ](https://github.com/gevgeny/angular2-webpack-starter-and-angular2-highcharts/commit/fffbebfd7974f808242dbbb8eccdfc108dde72cf#diff-f737fedb5357468044db2dbe98eb0218)

upd: I don't use angular cli, but I had the same problem.

**Comment by gevgeny** [comment]
@Tsvetkovv Bingo! At least someone looking in the readme!

**Comment by cedricleroy** [comment]
@Tsvetkovv : I assume you were not using angular cli, right?

**Comment by tsvetkovv** [comment]
@cedricleroy, right. I use angular2-webpack-starter

**Comment by gevgeny** [comment]
According to this https://github.com/angular/angular-cli/issues/1656 angular-cli contributors are not going to help you :(

**Comment by gevgeny** [comment]
You can try to use this hack http://stackoverflow.com/a/39189817/438084

**Comment by ftavilla** [comment]
Hi,

I found that you can alias highstock.js in tsconfig.ts file as following:

```json
  "compilerOptions": {  
      ...,  
      "paths": {  
          "highcharts": ["../node_modules/highcharts/highstock.js"]   
       }  
   }```

That will do the same thing as mention in the README for those using angular cli.

Hope it helps.

**Comment by Nazgrim** [comment]
@ftavilla Thanks man, it works.

**Comment by jyothish6190** [comment]
@ftavilla  Applied your fix above. but the highchart css not loading properly

**Comment by ftavilla** [comment]
Hi @jyothish6190 ,

Do you have an error in your web developper console? Can you provide more details please?
Here is some points to check:

Did you check if highcharts has been correctly added in your node-modules?
Did you import angular2-highcharts in your app.module.ts?

Here is a example of app.module.ts:

```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { ChartModule } from 'angular2-highcharts';


import { AppComponent } from './app.component';
import { BarchartComponent } from './chart/bar-chart.component';
@NgModule({
  declarations: [
    AppComponent,
    BarchartComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    ChartModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**Comment by jyothish6190** [comment]
@ftavilla : Now it works for me. thanks

**Comment by beabri** [comment]
I all, I have the same issue, but with the Chart Type "gauge". I don't use angular-cli neither webpack, only using systemjs.config.js.

Here my app.module.ts:

```
import { ChartModule } from 'angular2-highcharts';

@NgModule({
  imports: [
    ChartModule.forRoot('highcharts'),
    ChartModule.forRoot('highcharts/highcharts-more'),
    ChartModule.forRoot('highcharts/modules/solid-gauge'),
  ]
})
export class AppModule {
}
```


And my sistemjs.config.js:

```
        packages: {
            highcharts: {
                main: './highcharts.js',
                defaultExtension: 'js'
            },
            'angular2-highcharts': {
                main: './index.js',
                defaultExtension: 'js'
            }            
        },
     resolve: {
      alias: {
        // NOTE: You should set 'highcharts/highcharts.src.js'
        // if you are not going to use <chart type="StockChart"
        highcharts$: "highcharts/highcharts-more.src.js"
      }

```

What am I missing?

**Comment by beabri** [comment]
UPDATE: it seems not to be a gauge error... it doesn't work always with the simplest highchart inside my Angular 2 app, it always gives me the following error:

![schermata 2017-03-01 alle 12 43 21](https://cloud.githubusercontent.com/assets/16668179/23458784/e3bb39d6-fe7d-11e6-88de-5b8ada4fdb53.png)

Here my app.module.ts:

    import { ChartModule } from 'angular2-highcharts';
    
    @NgModule({
      imports: [
        ChartModule.forRoot('highcharts')
      ]
    })
    export class AppModule {
    }


My sistemjs.config.js:

        map: {
            'angular2-highcharts': 'npm:angular2-highcharts',
            'highcharts': 'npm:highcharts'
        },
        packages: {
            highcharts: {
                main: './highcharts.js',
                defaultExtension: 'js'
            },
            'angular2-highcharts': {
                main: './index.js',
                defaultExtension: 'js'
            }            
        }


And, inside my component:

    import { Component } from '@angular/core';
    import { ChartModule } from 'angular2-highcharts';
    
    @Component({
      selector: 'highchart',
      template: '<chart [options]="options">'
    })

    constructor() {
        this.options = {
            title : { text : 'angular2-highcharts example' },
            series: [{
                name: 's1',
                data: [2,3,5,8,13],
                allowPointSelect: true
            },{
                name: 's2',
                data: [-2,-3,-5,-8,-13],
                allowPointSelect: true
            }]
        };

        console.log(this.options);
    } 
    options: Object;


Any ideas? Thanks a lot.

**Comment by harishmegharaj** [comment]
Hi,
   The above problem got resolved, with below code in app.module.ts

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { ChartModule } from 'angular2-highcharts';
import { HighchartsStatic } from 'angular2-highcharts/dist/HighchartsService';

import { AppComponent } from './app.component';

declare var require: any;
export function highchartsFactory() {
  //return require('highcharts');
  const hc = require('highcharts');
  const dd = require('highcharts/modules/drilldown');
  const ex = require('highcharts/modules/exporting');
  const st = require('highcharts/modules/stock');

  dd(hc);
  ex(hc);
  st(hc);
  return hc;
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    ChartModule
  ],
  providers: [{ provide: HighchartsStatic, useFactory: highchartsFactory }],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by siomon0330** [comment]
where is the WebApiObservableService and  DataService?

**Comment by harishmegharaj** [comment]
Sorry, those were my internal service files. Please remove, it is not required this should work
providers: [{ provide: HighchartsStatic, useFactory: highchartsFactory }]

**Comment by siomon0330** [comment]
And I guess it is in the app.module.ts instead of app.component.ts? since there is no @NgModule in app.component.ts

**Comment by harishmegharaj** [comment]
Agree, i have done the changes as part of code

**Comment by leonardseymore** [comment]
> 
> 
> Hi,
> The above problem got resolved, with below code in app.module.ts
> 
> import { BrowserModule } from '@angular/platform-browser';
> import { NgModule } from '@angular/core';
> import { FormsModule } from '@angular/forms';
> import { HttpModule } from '@angular/http';
> import { ChartModule } from 'angular2-highcharts';
> import { HighchartsStatic } from 'angular2-highcharts/dist/HighchartsService';
> 
> import { AppComponent } from './app.component';
> 
> declare var require: any;
> export function highchartsFactory() {
> //return require('highcharts');
> const hc = require('highcharts');
> const dd = require('highcharts/modules/drilldown');
> const ex = require('highcharts/modules/exporting');
> const st = require('highcharts/modules/stock');
> 
> dd(hc);
> ex(hc);
> st(hc);
> return hc;
> }
> 
> @NgModule({
> declarations: [
> AppComponent,
> ],
> imports: [
> BrowserModule,
> FormsModule,
> HttpModule,
> ChartModule
> ],
> providers: [{ provide: HighchartsStatic, useFactory: highchartsFactory }],
> bootstrap: [AppComponent]
> })
> export class AppModule { }

I've been trying forever to get this working. Finally a solution that works. Thanks a mil!!!!!!
