### ISSUE TITLE
How to change HighCharts colors

### ISSUE THREAD

**Issue by Nolanus** [gevgeny/angular2-highcharts#102]
Previously I could do the following:

```
import {Highcharts} from 'angular2-highcharts';

Highcharts.setOptions({ /* Options here*/})
```

in order to set e.g. the default colors or spacings. How to perform this with the new v0.4.1 release?

**Comment by gevgeny** [comment]
https://github.com/gevgeny/angular2-highcharts#access-to-the-highcharts-static-members-and-modules
