### ISSUE TITLE
Update docs to match latest version

### ISSUE THREAD

**Issue by Nolanus** [gevgeny/angular2-highcharts#103]
Hi,

just updated to latest version 0.4.1 and got errors like "Cannot find name 'HighchartsOptions'."

Given that Searching the repo for these terms( [HighchartsOptions](https://github.com/gevgeny/angular2-highcharts/search?utf8=%E2%9C%93&q=HighchartsOptions) and and [HighchartsChartObject](https://github.com/gevgeny/angular2-highcharts/search?utf8=%E2%9C%93&q=HighchartsChartObject)) only reveals the README it would be nice to share the new names with us.

**Comment by gevgeny** [comment]
Yes, thanks

**Comment by skol-pro** [comment]
Why does HighchartsOptions has been removed ?

**Comment by gevgeny** [comment]
it was removed from the highcharts typings
