### ISSUE TITLE
chart not filling-up div

### ISSUE THREAD

**Issue by sspilleman** [gevgeny/angular2-highcharts#11]
See screenshot

I want the chart to nicely fill up the area. Is this a bug? Or am I doing something wrong?

Thanks!

HTML

```
<div class="chart-wrapper">
    <chart class="chart" [options]="options"></chart>
</div>
```

CSS

```
.chart {
    border: 3px solid yellow;
    width: 100% !important;
}

.chart-wrapper {
    border: 3px solid orangered;
    width: 100% !important;
}
```

[![bug](https://dl.dropboxusercontent.com/u/182851/angular2-highcharts.bug.png)]

**Comment by gevgeny** [comment]
I think this is not the library's issue. Google how to make highcharts chart max width.

**Comment by sspilleman** [comment]
You're probably right.... I fixed it by applying "display:block" to the chart div.... Must be the bootstrap class "container" leaking onto your component or something. You may want to add it to the docs though

**Comment by gevgeny** [comment]
The main live demo in the readme shows how to do this http://plnkr.co/edit/pnkc8Iw9cSrCYn9zr0VZ?p=preview

**Comment by born2net** [comment]
do this:
```
chart {
    width: 100% !important;
    margin: 0 auto;
    display: block;
}
```

**Comment by sachinmishra007** [comment]
Hi,

If you are burning all midnight oil for this.I would 
just suggest to make use existing class of the charts
Which helps to adjust the size of the image
i.e.

.highcharts-root{
         width:500px !important;
         display:block;
  }
