### ISSUE TITLE
getting an error when loading a type='Map' chart

### ISSUE THREAD

**Issue by xavierclotet** [gevgeny/angular2-highcharts#111]
Hi I'm getting the follow error trying to run a type='Map'

Error: Map is unknown chart type.
    at Object.initChart (http://localhost:4300/0.chunk.js:591:15)
    at ChartComponent.init (http://localhost:4300/0.chunk.js:277:38)
    at ChartComponent.ngAfterViewInit (http://localhost:4300/0.chunk.js:283:14)
    at DebugAppView.View_DashboardDemographicComponent0.detectChangesInternal (/DashboardModule/DashboardDemographicComponent/component.ngfactory.js:316:73)

etc

This is when i write: ` <chart type="Map" [options]="optionsMap"></chart>`

The other charts are loading , ok.

**Comment by gevgeny** [comment]
Looks like you have not plugged maps module. See the appropriate readme section

**Comment by sanketsw** [comment]
add missing module to the highcharts factory. I got this error when i was missing `require('highcharts/modules/map')(hc);`

Here is my code after i fixed it
```

export function highchartsFactory() {
    const hc = require('highcharts');
    require('highcharts/modules/heatmap')(hc);
    require('highcharts/modules/map')(hc);
    require('highcharts/modules/drilldown')(hc);
    require('highcharts/modules/exporting')(hc);
    require('highcharts/modules/offline-exporting')(hc);
    require('highcharts/modules/export-data')(hc);
    return hc;
}
```
Add the highchartsFactory to the providers
```
providers: [
        {
            provide: HighchartsStatic,
            useFactory: highchartsFactory
        }
    ],
```
