### ISSUE TITLE
3D not working with 0.4.x

### ISSUE THREAD

**Issue by michael-brade** [gevgeny/angular2-highcharts#112]
Hi, there is no example for `angular2-highcharts` that uses `highcharts-3d`. I have been trying quite a bit but without any luck. I am using it with Ionic 2, but at this point Ionic is not the reason.

Examples:

```
import { Highcharts } from 'angular2-highcharts';
import Highcharts3d from 'highcharts/highcharts-3d';
Highcharts3d(Highcharts);
```
leads to
```
11:32:28]  Module '"node_modules/angular2-highcharts/index"' has no exported 
            member 'Highcharts'. 
[11:32:28]  ngc failed 
```

This
```
import Highcharts from 'highcharts/highcharts';
import Highcharts3d from 'highcharts/highcharts-3d';
Highcharts3d(Highcharts);
```
compiles but still shows 2D charts.

How do you achieve 3D charts with angular2-highcharts?

**Comment by gevgeny** [comment]
see https://github.com/gevgeny/angular2-highcharts#installation

**Comment by michael-brade** [comment]
Yes, I did read that, and tried it before without success, but I don't remember the error message.
Doesn't matter, because now, with this code

```
import * as Highcharts from 'highcharts';
import * as Highcharts3d from 'highcharts/highcharts-3d';

Highcharts3d(Highcharts);
```

and these versions:

```
   "angular2-highcharts": "0.4.1",
   "highcharts": "5.0.2",
   "@types/highcharts": "4.2.40"
```

it finally works! Thanks!

**Comment by gevgeny** [comment]
you don't need install highcharts at all.
