### ISSUE TITLE
Drilldown event is not getting fired 

### ISSUE THREAD

**Issue by ruchitomar** [gevgeny/angular2-highcharts#113]
I am using typescript and webpack in my angular2 project but when I click on the chart 'drilldown' event is now getting fired or is there any other way to work with drilldown rather then calling drilldown event .

**Comment by gevgeny** [comment]
plz provide live demo

**Comment by ruchitomar** [comment]
[angular-webpack.zip](https://github.com/gevgeny/angular2-highcharts/files/601941/angular-webpack.zip)

Please find the live example . I tried to use drilldown as chartevent and also tried with the options as drilldown:"abc" to app.components.ts but both are not working. Please help.Thanks a lot!

**Comment by gevgeny** [comment]
could you plz create plunker or jsfiddle based on one of the live demos from the readme ?

**Comment by ruchitomar** [comment]
Take a look at the following Plunker 
http://plnkr.co/edit/5h7jNKVu4rRuO6k7Vwv6

**Comment by gevgeny** [comment]
you need to plug appropriate highcharts module in order this event to work. See this section https://github.com/gevgeny/angular2-highcharts#access-to-the-highcharts-static-members-and-modules

**Comment by ruchitomar** [comment]
Thanks a lot.It's working now with highcharts .I was assumimg that it will work with ChartModule --'angular2-highcharts'.

**Comment by gevgeny** [comment]
np
