### ISSUE TITLE
HighStocks

### ISSUE THREAD

**Issue by bencameron00** [gevgeny/angular2-highcharts#117]
Hi

Love your HighCharts wrapper, thank you!

I am trying to use HighStocks by copying your plnkr demo at http://plnkr.co/edit/2xSewTZ9b213vA0ALmFq?p=preview

I was hoping you could help me?

I am not sure how to import  the below when I don't have a systemjs.config.js in my Ng2 app...

'angular2-highcharts':        'https://cdn.rawgit.com/gevgeny/angular2-highcharts/v0.3.0/dist', 
'highcharts/highstock.src':   'https://cdn.rawgit.com/highcharts/highcharts-dist/v4.2.1/highstock.js'

I am seeing the below error...

core.umd.js?e2a5:3004 EXCEPTION: Error in ./XXX class XXX- inline template:1:25 caused by: StockChart is unknown chart type.

I know that I have missed importing something correctly but I can't figure out how to do this in my app.

Do you have any ideas?
Thank you

**Comment by gevgeny** [comment]
do you use systemjs or webpack or some other bundler tool ?

**Comment by bencameron00** [comment]
Hi

Thank you for you’re your response.

I am using webpack.

**Comment by gevgeny** [comment]
So i makes sense to look at appropriate installation section https://github.com/gevgeny/angular2-highcharts#installation

**Comment by bencameron00** [comment]
Hi, I have followed the instructions and normal HighCharts work fine. The problem is that I cannot use HighStocks. 
I've uploaded an example to [github.com/bencameron00/HighStocksSetup](url) . As you can see in mainViewer.component.html the type attribute is causing the issue.
What have I missed out? Any help would be appreciated.

**Comment by bencameron00** [comment]
After doing some more reading it seems a few people have had trouble using HighStocks. The issue seems to be HighStocks into various webpack and systemjs setups.
Do you think you will be further wrapping HighStocks into your component so that its completely self contained and no build configuration needs to be done? That would be really great!
