### ISSUE TITLE
Exporting Functionality

### ISSUE THREAD

**Issue by ghost** [gevgeny/angular2-highcharts#121]
Is the Exporting to PDF/PNG/... feature available in this release?

**Comment by gevgeny** [comment]
yes

**Comment by ghost** [comment]
Really? Because I can't seem to enable it. Maybe you could be a little more explicit and possibly helpful? There is nothing in your docs or any demos that show that the export to pdf feature has been included/can be used. Maybe I am missing where you demonstrated this. Can you point me to the right place please?

**Comment by gevgeny** [comment]
The Highcharts functionality is huge and I really cannot cover all the cases in the docs. But I hope it is clear from the doc that it is just a wrapper for the Highcharts. And if you have read the higcharts doc so you should know that the exporting functionality feature (like tens of others) is the pluggable highcharts module. So you can check out appropriate readme section https://github.com/gevgeny/angular2-highcharts#access-to-the-highcharts-static-members-and-modules. Hope this helps.

**Comment by ghost** [comment]
Yes, I am aware of all of this thank you. I understand it is a wrapper and I am also familiar with Highcharts as it exists, since I have used it in several projects in the past -- a few of those using Angular 1 in fact. I was just having some difficulty getting the exporting functionality implemented in this particular wrapper. I am sorry to bother you and use this forum for this purpose, but like I said I just came across some obstacles using the Highcharts features in this particular library and I thought I would reach out to someone who is more knowledgeable than myself in this area. I didn't expect a comprehensive explanation into the details of Highcharts, rather I was just looking for a little help on this particular module, which I have received. So, thank you for your assistance. I really appreciate you taking the time to do so.
