### ISSUE TITLE
Question: how to call chart.reflow()

### ISSUE THREAD

**Issue by crh225** [gevgeny/angular2-highcharts#123]
I need to call a chart function called reflow(). this seems to be the issue with highcharts and angular 2 when you show/hide the container, and not your repo.

 I want it to be 100% width responsive chart. The container is a simple <div> with no any formatting. When the document loads, the chart is always fixed width 600x400px size. If I resize window or switch to another browser tab, the chart fills the width and becomes responsive full width chart just like I wanted. If I reload page, it's fixed width again. I tried setting width to both container and chart, however, nothing helps. I have tried to display: block also.

the issue is the Chart's width is taken from width(container), so if you have chart in some hidden tabs or something similar, width will be undefined. In that case default width and height are set (600x400). So I want to hide the chart until data exists, but when the chart is drawn, the width is undefined. When the chart has data, I need to call the reflow.

The chart object has a reflow() function.

**Comment by gevgeny** [comment]
you have access to all the native highcharts API. See examples https://github.com/gevgeny/angular2-highcharts#access-to-the-highcharts-static-members-and-modules

**Comment by crh225** [comment]
@gevgeny that both of those links do not access any of the charts static memeber or functions. I would expect to see something like chart.property

**Comment by crh225** [comment]
import * as Highcharts from 'highcharts';

this is not an answer to my question.

**Comment by crh225** [comment]
here is my plunkr: http://plnkr.co/edit/GVfReOzrA8plc2izCQZm?p=preview

**Comment by crh225** [comment]
yarn remove angular2-highcharts

**Comment by gevgeny** [comment]
the very first demo in the readme treating with chart instance http://plnkr.co/edit/pnkc8Iw9cSrCYn9zr0VZ?p=preview. the rest you need you can find the highcharts API

**Comment by crh225** [comment]
@gevgeny 
is there not a way to have an input of chartData to your component, and then so your package could call reflow when ngOnChanges gets fired?
```
@ViewChild('chart') public chartEl: ElementRef;
@Input()
public chartData: any;
ngOnChanges(){
        if (this.chartData) {
            //this options
            this.opts = this.chartData;
            if (this.chartEl && this.chartEl.nativeElement) {
                this.opts.chart = {
                    renderTo: this.chartEl.nativeElement
                };

                this._chart = new Highcharts.Chart(this.opts);
                this._chart.reflow();

            }
        }
}
```
and the html
```
<div #chart class="chart-widget"></div>
```

**Comment by gevgeny** [comment]
no, see the FAQ https://github.com/gevgeny/angular2-highcharts#why-dont-my-series-title-axes-and-etc-redraw-after-i-update-initial-options-

**Comment by sorcamarian** [comment]
This is how I solved the problem:

**HTML**
```
<!-- The if statement will remove the chart from the DOM once the Array series has no elements -->
<div *ngIf="opts.series.length" [options]="opts" #chart class="chart-widget"></div>
```

**TypeScript**
```
generateChartData(data){

  let addNewData = () => {
    // add new data into opt.series
    data.forEach( (dataElement) => {
      this.opt.series.push({
        id: dataElement.id,
        name: dataElement.name,
        data: [dataElement.data],
      });
    })
  }

  // remove the current values
  if (this.opts.series.lenght) {
    // will remove the chart from the DOM because the if statement evaluates to false
    // <div *ngIf="opts.series.length" #chart class="chart-widget"></div>
    this.opts.series.lenght = 0;
  }
  // after a few secconds add the new data and make the if statement evaluate to true
  // the setTimeoutt is used in order to allow Angular to remove the chart from the DOM 
    // and adding it again once new data is added
   // this makes the chart reload again - I observed this with (load)="onChartLoad($event)" -  <div *ngIf="opts.series.length" (load)="onChartLoad($event) [options]="options"" #chart class="chart-widget"></div>
  setTimeout(addNewData, 1500);

}
```
