### ISSUE TITLE
deleted - non issue

### ISSUE THREAD

**Issue by crh225** [gevgeny/angular2-highcharts#125]
http://plnkr.co/edit/GlOaAdMoRzlM2OHyQfMn?p=preview

toggle show hide of the series using the bottom button.

when you hide series 0, your code is saying I selected a point when I didn't. 

update: this was user error. my apologies.

**Comment by gevgeny** [comment]
there are no any bugs. You click button then `hideSeries` is called and `onSeriesHide` is fired. what is wrong ?
