### ISSUE TITLE
Error:(13, 37) TS2305:Module ''highcharts'' has no exported member 'ChartObject'.

### ISSUE THREAD

**Issue by born2net** [gevgeny/angular2-highcharts#131]
Getting the following errors:

Error:(13, 37) TS2305:Module ''highcharts'' has no exported member 'ChartObject'.
Error:(5, 50) TS2305:Module ''highcharts'' has no exported member 'SeriesObject'.
Error:(5, 101) TS2305:Module ''highcharts'' has no exported member 'AxisObject'.

![capture](https://cloud.githubusercontent.com/assets/5090936/21065052/3693e050-be13-11e6-891e-89c204fdfb4f.PNG)

any ideas?

regards

Sean

**Comment by born2net** [comment]
fixed.

**Comment by Sally-Xu** [comment]
Getting the same "highcharts has no exported member 'ChartObject'" error after update highcharts to 7.0.0 ( highcharts 6.2 works fine)

using highcharts-angular version 2.3.1

**Comment by njifares** [comment]
Having the same issue after updating to version 7.0.1.
