### ISSUE TITLE
EXCEPTION: StockChart is unknown chart type.

### ISSUE THREAD

**Issue by demiro** [gevgeny/angular2-highcharts#132]
I had highcharts with HighStock chart working...

when I updated... from **0.3.4**  to **0.4.1**

I got the exception mentioned in the title
`EXCEPTION: StockChart is unknown chart type.`

It works fine if I remove 

> type="StockChart"

from the chart component.... resulting to default type...
I also updated angular to 2.3.1 if that could be an issue

**Comment by gevgeny** [comment]
you need to specify highstock in the webpack/systemjs config. see the installation step in the readme
