### ISSUE TITLE
HighStocks: issue with adding a plotBand

### ISSUE THREAD

**Issue by demiro** [gevgeny/angular2-highcharts#134]
I recently updated from **0.3.4** to **0.4.1**
and have a few issues.... one big one is that

this.chartInstance.xAxis[0].addPlotBand({
    from: date2,
    to: date3,
    color: '#e5f2f8',
    label:{ text: 'BAND 1',align:'center',verticalAlign:'bottom',y:-10,style:{color:'#666666',fontSize:'11px'}
}});

this.chartInstance.xAxis[0].addPlotBand({
    from: date1,
    to: date2,
    color: '#FFFFFF',
    label:{ text: 'BAND 2',align:'center',verticalAlign:'bottom',y:-10,style:{color:'#666666',fontSize:'11px'}
}});

Not working anymore... no bands are drawn.... (the labels are there though... correct location)

**Comment by gevgeny** [comment]
could you plz provide online demo ? (you also were asked in the the new issue text are)

**Comment by demiro** [comment]
Hello gevgeny..thanks for getting back at me this fast

Sadly I cannot.. it's a corporate site with very restricted environment.... had to.open the issue on my phone 😑

Its very straight forward... if you call.those two methods should see the bands... but see all grey

**Comment by gevgeny** [comment]
Seems the issue is more about highcharts rather than this wrapper since you work with its API directly in the example above

**Comment by demiro** [comment]
Well..it was working great before...has the highchart version changed as well in your library?

**Comment by demiro** [comment]
I solved it by using className property instead and setting the fill and fill-opacity... works now

**Comment by gevgeny** [comment]
> has the highchart version changed as well in your library?

yes
