### ISSUE TITLE
StockChart is unknown chart type for 0.4.1 version

### ISSUE THREAD

**Issue by elther** [gevgeny/angular2-highcharts#141]
I've tested StockChart for 0.4.1 version. it dosen't work. 
i got message "stockchart is unknown chart type"
so i changed engine 0.3.4 then StockChart's working well 

could you check this problem?

**Comment by raugaral** [comment]
I have the same problem.

**Comment by gevgeny** [comment]
Could you please specify more details ? what kind bundler do you use ? did you follow the instructions from this section https://github.com/gevgeny/angular2-highcharts#installation ?

**Comment by bencameron00** [comment]
I have followed the instructions but am having the same problem. I have posted a basic example to github. It would be nice if you could please take a quick look and help out. 
https://github.com/bencameron00/Ng2HighStocks

**Comment by gevgeny** [comment]
did you specify this https://github.com/gevgeny/angular2-webpack-starter-and-angular2-highcharts/blob/fffbebfd7974f808242dbbb8eccdfc108dde72cf/config/webpack.common.js#L73 ?

**Comment by bencameron00** [comment]
That's it, That's what i missed! Thank you!

**Comment by raugaral** [comment]
What should I do with this file or with this line??

**Comment by gevgeny** [comment]
this is part of an example config which you should add to your config

**Comment by raugaral** [comment]
I don't have this config files

**Comment by beabri** [comment]
I all, I have the same issue, but with the Chart Type "gauge". I don't use angular-cli neither webpack, only using systemjs.config.js.

Here my app.module.ts:

```
import { ChartModule } from 'angular2-highcharts';

@NgModule({
  imports: [
    ChartModule.forRoot('highcharts'),
    ChartModule.forRoot('highcharts/highcharts-more'),
    ChartModule.forRoot('highcharts/modules/solid-gauge'),
  ]
})
export class AppModule {
}
```


And my sistemjs.config.js:

```
        packages: {
            highcharts: {
                main: './highcharts.js',
                defaultExtension: 'js'
            },
            'angular2-highcharts': {
                main: './index.js',
                defaultExtension: 'js'
            }            
        },
     resolve: {
      alias: {
        // NOTE: You should set 'highcharts/highcharts.src.js'
        // if you are not going to use <chart type="StockChart"
        highcharts$: "highcharts/highcharts-more.src.js"
      }

```

What am I missing?

**Comment by gevgeny** [comment]
@beabri check this https://github.com/gevgeny/angular2-highcharts#for-systemjs-environment

**Comment by beabri** [comment]
@gevgeny I did exactly like in the example, but also with the simple chart it gives me the same error: "Chart is unknown chart type".

**Comment by beabri** [comment]
UPDATE: it seems not to be a gauge error... it doesn't work always with the simplest highchart inside my Angular 2 app, it always gives me the following error:

![schermata 2017-03-01 alle 12 43 21](https://cloud.githubusercontent.com/assets/16668179/23458784/e3bb39d6-fe7d-11e6-88de-5b8ada4fdb53.png)

Here my app.module.ts:

    import { ChartModule } from 'angular2-highcharts';
    
    @NgModule({
      imports: [
        ChartModule.forRoot('highcharts')
      ]
    })
    export class AppModule {
    }


My sistemjs.config.js:

        map: {
            'angular2-highcharts': 'npm:angular2-highcharts',
            'highcharts': 'npm:highcharts'
        },
        packages: {
            highcharts: {
                main: './highcharts.js',
                defaultExtension: 'js'
            },
            'angular2-highcharts': {
                main: './index.js',
                defaultExtension: 'js'
            }            
        }


And, inside my component:

    import { Component } from '@angular/core';
    import { ChartModule } from 'angular2-highcharts';
    
    @Component({
      selector: 'highchart',
      template: '<chart [options]="options">'
    })

    constructor() {
        this.options = {
            title : { text : 'angular2-highcharts example' },
            series: [{
                name: 's1',
                data: [2,3,5,8,13],
                allowPointSelect: true
            },{
                name: 's2',
                data: [-2,-3,-5,-8,-13],
                allowPointSelect: true
            }]
        };

        console.log(this.options);
    } 
    options: Object;


Any ideas? Thanks a lot.

**Comment by kleberksms** [comment]
App.Module
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { ChartModule } from 'angular2-highcharts';

export function highchartsFactory() {
  const hc = require('highcharts');
  const dd = require('highcharts/modules/drilldown');
  const ex = require('highcharts/modules/exporting');
  const st = require('highcharts/modules/stock');

  dd(hc);
  ex(hc);
  st(hc);
  return hc;
}

@NgModule({
 providers: [
{ provide: HighchartsStatic, useFactory: highchartsFactory }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }


Component
import { Component, OnInit } from '@angular/core';
import * as HighchartsTyping from 'highcharts';

import { HighchartsOptions } from './../../_helpers/highcharts/highcharts-options';

@Component({
  selector: 'app-onion-track',
  templateUrl: './onion-track.component.html',
  styleUrls: ['./onion-track.component.sass']
})
export class OnionTrackComponent implements OnInit {

  private highcharts: HighchartsOptions;
  public chart: HighchartsTyping.ChartObject;
  public options: Object;


  constructor() {
    this.highcharts = new HighchartsOptions();
    HighchartsTyping.setOptions(this.highcharts.Theme('darkunica'));

    this.options = {
      title: { text: 'AAPL Stock Price' },
      series: [{
        name: 'AAPL',
        data: [
          [1280966400000, 37.39],
          [1281052800000, 37.16],
          [1281312000000, 37.39],
        ],
        tooltip: {
          valueDecimals: 2
        }
      }]
    };

  }

  saveInstance(chartInstance) {
    this.chart = chartInstance;
  }

  ngOnInit() {
    setInterval(() => {
      if (this.chart.series[0].data.length > 15) {
        this.chart.series[0].data[0].remove();
      }
      this.chart.series[0].addPoint(Math.random() * 10);
    }, 1000);

  }

}


Template Html
<div class="container-bp">
  <div class="row templates">
    <div class="col s12">
      <br>
      <chart type="StockChart" [options]="options" (load)="saveInstance($event.context)"></chart>
    </div>
  </div>
</div>
