### ISSUE TITLE
Systemjs of how to use module and plugin  / exporting module

### ISSUE THREAD

**Issue by dhagan** [gevgeny/angular2-highcharts#142]
Great module so far!  Thank you.

Would be very helpful to have an example of including a module and plugin - specifically the exporting moudle with a csv plugin
 
https://github.com/angular/angular-cli/issues/1000

**Comment by gevgeny** [comment]
there is nothing tricky in adding plugins to a systemjs app. Here is the example for highchart-3d added https://github.com/gevgeny/angular2-quickstart-and-angular2-highcharts/commit/5021ff2b7f615a5b566b4bab0faf70991f5a53db
