### ISSUE TITLE
Error with NativeScript and WebPack

### ISSUE THREAD

**Issue by anafreitas** [gevgeny/angular2-highcharts#143]
Hi, I'm trying to use this plugin with NativeScript and WebPack. I followed the insructions on this [repository](https://github.com/gevgeny/angular2-webpack-starter-and-angular2-highcharts), but I'm having this error:

`ERROR in Unexpected value 'ChartModule' imported by the module 'AppModule'`

What can be wrong?

Here is a link to [my repository](https://github.com/anafreitas/testeNativeScriptWebPack)

**Comment by gevgeny** [comment]
I don't think it is possible to use highcharts with native script since it uses DOM and native script doesn' t. Sorry
