### ISSUE TITLE
Responsive chart is not working

### ISSUE THREAD

**Issue by mohyeid** [gevgeny/angular2-highcharts#146]
I am trying to apply responsive property to the options, but it does not work. Live demo from : http://www.highcharts.com/demo/responsive 
I applied the same options, but the chart is not responsive. 

Here is a plnkr example:

https://plnkr.co/edit/KQcJT2EQDMsbd562j9hv?p=preview

**Comment by mohyeid** [comment]
This seems to be working if I added display: block. It works in my local, but does not work exactly in plnkr. I will confirm everything is good on my local and close this issue tomorrow.

**Comment by woshisbb43** [comment]
thansk
