### ISSUE TITLE
type=StockChart seems to have been broken in 0.4.0

### ISSUE THREAD

**Issue by nnarendravijay** [gevgeny/angular2-highcharts#149]
<chart type="StockChart" [options]="options"></chart> works with angular2-highcharts version 0.3.0, but with 0.4.0, we get "Unknown chart type StockChart".

**Comment by raugaral** [comment]
I have the same problem. 
The solution is using the configuration on https://github.com/gevgeny/angular2-highcharts#installation (Webpack or SystemJS) but the real problem is if do you know were are this configuration files.

I'm using Ionic 2 and I don't have this config files...

**Comment by raugaral** [comment]
@nnarendravijay only remove type="StockChart"

**Comment by gevgeny** [comment]
See updates in the readme
