### ISSUE TITLE
Highcharts exporting

### ISSUE THREAD

**Issue by 4sur3** [gevgeny/angular2-highcharts#15]
Hi guys

Did you try to use the highcharts exporting tool (Client side export)  ?

I'm following the higcharts documentation :
[http://www.highcharts.com/docs/export-module/client-side-export](http://www.highcharts.com/docs/export-module/client-side-export)
jsfiddle:
[http://goo.gl/yeKhh4](http://goo.gl/yeKhh4)

But it doesn't work.

Thanks in advance.

**Comment by gevgeny** [comment]
How is it related to angular2-highcharts ?

**Comment by 4sur3** [comment]
Hi
Because I created an angular component using angular2-highcharts and I set the options to display the exporting button.

**Comment by gevgeny** [comment]
Did you try to plug module like it is specified in the readme https://github.com/gevgeny/angular2-highcharts#using-highchart-modules ?
