### ISSUE TITLE
Has there been a angular cli example for integrating angular2-highcharts

### ISSUE THREAD

**Issue by automatedenergy** [gevgeny/angular2-highcharts#153]
Does anyone have a workflow for integrating angular2-highcharts with angular-cli projects. I am having difficulty still and would really like to use this repository. Thanks. John

**Comment by gevgeny** [comment]
I am trying to changing API so you should not change webpack or systemjs config it should simplify usage the library with angular-cli. I also created this issue https://github.com/highcharts/highcharts/issues/6364 in the highcharts repo

**Comment by gevgeny** [comment]
Finally I added angular-cli support. But unfortunately with small API changes. See updated [readme](https://github.com/gevgeny/angular2-highcharts/blob/master/README.md) and [release notes](https://github.com/gevgeny/angular2-highcharts/releases/tag/v0.5.4). Let me know whether it works
