### ISSUE TITLE
module is not a function ...

### ISSUE THREAD

**Issue by mikeplavo** [gevgeny/angular2-highcharts#155]
Hello guys,
I would like to have charts (area type) and maps on the same page.

in my app.module.ts : 
`
        ChartModule.forRoot(
            require('highcharts'),
            require('highcharts/highmaps')
        ),
`
 I have the following error: 
`module is not a function at eval (http://localhost:3000/node_modules/angular2-highcharts/dist/index.js:36:13`

I can use  require('highcharts'), alon and see my charts or require('highcharts/highmaps') alone and see the maps but I can't use them both.

Any ideas

**Comment by gevgeny** [comment]
This is because `require('highcharts/highmaps')` is not module for highcharts.  You have two variants here:
- `ChartModule.forRoot(require('highcharts/highmaps'))`
or
- `ChartModule.forRoot(require('highcharts'), require('highcharts/modules/map'))`

**Comment by mikeplavo** [comment]
It's work. Thanks you so much
Maybe you should write it in the documentation for newbie like me.
