### ISSUE TITLE
How to import two chart types for root?

### ISSUE THREAD

**Issue by zilions** [gevgeny/angular2-highcharts#159]
I am attempting to import two chart types for my root app, being the basic Highcharts and HighStock. I have tried the below, with no success.

The below returns an error of `Uncaught TypeError: module is not a function`.
```
ChartModule.forRoot(
     require('highcharts'),
     require('highcharts/highstock')
)
```

**Comment by gevgeny** [comment]
Just 

```
ChartModule.forRoot(
     require('highcharts/highstock')
)
```

**Comment by zilions** [comment]
And what if I wanted to use both Highstock and Highmaps?

**Comment by gevgeny** [comment]
Highmaps can be added as a modules read the highcharts modules spec
