### ISSUE TITLE
angular/2.0.0-rc.1

### ISSUE THREAD

**Issue by RohitLuthra19** [gevgeny/angular2-highcharts#16]
Hi,

Can you please update to @angular/2.0.0-rc.1?

Thank you!!

**Comment by Svancara** [comment]
Hi!

Please, please, update to AngularJS 2 RC.1.

Thank you very much!

**Comment by dmcclureagl** [comment]
- 1 on this, our current project is blocked due to lack of upgrade to RC.

Will have to resume on old code till then.

**Comment by gevgeny** [comment]
Hi guys!
Sorry for the delay. Will update in the coming days. But if you can pull request with working tests and examples it would be great.

**Comment by gevgeny** [comment]
Just published `angular2-highcharts@0.1.0` with migration to RC.1
