### ISSUE TITLE
Include boost.js from highcharts

### ISSUE THREAD

**Issue by Wandang** [gevgeny/angular2-highcharts#161]
I tried to add around 100 points/second to my chart but this produces severe performance issues.

Highchart provides an experimental boost.js http://www.highcharts.com/news/175-highcharts-performance-boost/

It would be great if this could be included

**Comment by gevgeny** [comment]
It is. see the readme

**Comment by dales** [comment]
Where in the readme is it? Is it supported?

**Comment by ghostofcain** [comment]
It's the same as the other modules.

import {ChartModule, HIGHCHARTS_MODULES} from 'angular-highcharts';
import * as boost from 'highcharts/modules/boost.src';

@NgModule({
{
             ...
            providers: [
                 ...
                 {
                    provide: HIGHCHARTS_MODULES,
                   useFactory: () => [boost // and whatever else you need to import],
                 }
            ]
},
