### ISSUE TITLE
Display settings 

### ISSUE THREAD

**Issue by lazywhite** [gevgeny/angular2-highcharts#19]
I don't know how to set the width and height of chart,   I tried to pass width, height settings and set css attribute , both dosen't work ,  maybe it's hard coded? I always get width:600px; height: 400px;

**Comment by gevgeny** [comment]
Did you look at the live examples from the readme ?

**Comment by gevgeny** [comment]
angular-hihgcharts does not change any default display settings

**Comment by pranshuagrawal** [comment]
@lazywhite did you manage to fix that? I am also facing the same issue. 

No matter what I set the height and width of the parent container, highcharts inner div.highcharts-container  and the svg has height and width of 600px and 400px respectively.

**Comment by tonym99** [comment]
Has anyone figured this one out?  I too have a width and height of 600px and 400px respectively no matter what the browser is narrowed to.

Anyone??

**Comment by pranshuagrawal** [comment]
@tonym99  Yea so the solution I have figured out is to set the `display` property of chart element to `block`.

```
chart{
   display: block;
}
```

**Comment by tonym99** [comment]
Thanks!!
