### ISSUE TITLE
Graphical problem with angular material

### ISSUE THREAD

**Issue by JulesFaucherre** [gevgeny/angular2-highcharts#194]
Hello,

I am using angular 4 with angular material and there is problems drawing charts inside a tab with an ngFor.
I created a new app with angular-cli and added just angular-material2 and angular2-highcharts.

Here is a gist of my app.component.ts and my app.component.html and an image of the result. The problem does not happen where there is no ngFor
<img width="626" alt="capture d ecran 2017-06-02 a 22 27 43" src="https://cloud.githubusercontent.com/assets/26357621/26743604/c7ca24ea-47e2-11e7-8a73-ceb6d3ba7bee.png">

**Comment by gevgeny** [comment]
How is it related to angular2-highcharts ?

**Comment by JulesFaucherre** [comment]
Because even if the problem appears with the angular for loop, the rendering is made with angular2-highcharts so maybe someone can help me about it.

And sorry I did not give the link for the gist: https://gist.github.com/JulesFaucherre/e09a0711d35f5958e13561e6da59a29e
