### ISSUE TITLE
reflow not working in single click

### ISSUE THREAD

**Issue by Abhishek-lodha** [gevgeny/angular2-highcharts#195]
I am using ChartModule to display my charts with tabs. 
When user clicks on tab, I am trying to use **chart.nativeChart.reflow()**. This method doesn't work when the user clicks on the tab one time. 
But it gets called when the tab is pressed twice.

Component.ts
`tabs = [];
 charts = [];
 this.charts.push({
        options: this.defaultConfig,
        nativeChart: null // To be obtained with saveInstance
      });
 chartReflow(tab): void {
    this.charts.forEach(chart => {
       chart.nativeChart.reflow();
    });
  }
 saveInstance(chartInstance, chart) {
    chart.nativeChart = chartInstance;
  }
`

component.html
`<div>
  <tabset [justified]="true">
    <tab *ngFor="let tab of tabs" [heading]="tab.heading" [id]="tab.id" (select)="chartReflow(tab.id)">
      <div class="row">
        <div *ngFor="let div of tab.showDivs" [class]="div.class">
            <div [id]="div.id"></div>
        </div>
      </div>
    </tab>
  </tabset>

  <div *ngFor="let chart of charts">
    <chart [options]="chart.options" (load)="saveInstance($event.context, chart)"></chart>
  </div>
</div>`

**Comment by Abhishek-lodha** [comment]
Solved the issue by calling reflow in my constructor.

**Comment by akshay0910-asnl** [comment]
@Abhishek-lodha -: can you please share your code?Not really understanding how the code flow goes into the constructor

**Comment by Abhishek-lodha** [comment]
@akshay0910-bits : 
`constructor(){
    this.charts.forEach(chart => { chart.nativeChart.reflow(); });
}`
