### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'chart'.

### ISSUE THREAD

**Issue by ibenettaleb** [gevgeny/angular2-highcharts#207]
Plz Help !
<img width="930" alt="help" src="https://user-images.githubusercontent.com/28574987/27786175-056eba74-5fd8-11e7-9dc1-03c3f2e5b5a6.png">

**Comment by Ghernouz** [comment]
Hi,
I got the same issue did you find any solutions? 
Thanks

**Comment by fatjoni** [comment]
All the problems arise when using prerendering. This module uses extensively the DOM. This means that you should include all your modules in the client main module not in the server module

**Comment by jayeshkorat18** [comment]
I got the same issue did you find any solutions?

**Comment by sfate** [comment]
You need to specify `ChartModule` at imports section for your module which is loading the component with a highchart.

**Comment by akandach** [comment]
seeing the same issue. Any update on this?

**Comment by eddyoc** [comment]
Same issue. modules all included in app.module.

**Comment by sfate** [comment]
If you have any child modules you need to include `ChartModule` there instead of `app.module`

**Comment by tskweres** [comment]
same issue, and if i try to put the <chart> into a parent component it persists

**Comment by sunilverma003** [comment]
I was facing the same issue. I resolved it by include **ChartModule** into child module instead of **app.module**.

**Comment by dougmolineux** [comment]
I am experiencing this error as well, when I try to load the component in a unit test.

Update: I was able to get this working by importing the module as an "import" in the TestBed configuration:

```
import { ChartModule } from 'angular2-highcharts';
...
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpModule,
        ChartModule,
```

**Comment by ibenettaleb** [comment]
Thx 🙏 for your answer
