### ISSUE TITLE
Chart does not refresh/redraw when adding multiple series

### ISSUE THREAD

**Issue by chris-hq** [gevgeny/angular2-highcharts#22]
I've got the data for each series coming down from a call to the database. They get added to a javascript object and that gets attached to the chart element as the options attribute. Whichever comes back first is the only one that is displayed.

I see in highcharts there is a redraw function and see how with your repository to handle when that function is called, but unless there is some way to call it I think there is a problem for dynamic series.

**Comment by gevgeny** [comment]
Could you plz provide plunkr or fiddle with the issue ?

**Comment by chris-hq** [comment]
figured out a work around after pounding my head against a wall.

**Comment by gevgeny** [comment]
:)

**Comment by rachelmad** [comment]
@chris-hq How did you work around this? I'm having redraw issues as well.

**Comment by chris-hq** [comment]
Instead of manually calling the redraw function I instead used the addSeries function on the chart object. the addSeries function 2nd parameter is a redraw boolean. Hope this helps.

`<chart [options]="options" (load)="saveInstance($event.context)"></chart>`

`chart: HighchartsChartObject;
    saveInstance(chartInstance: any) {
        this.chart = chartInstance;
    }`

```
if (this.chart) {
            this.chart.addSeries(o.json(), true)
        }
```
