### ISSUE TITLE
how can I import the highcharts-more.js in to app.module.ts

### ISSUE THREAD

**Issue by tungphien** [gevgeny/angular2-highcharts#228]
Hi @gevgeny , all
Here is my app.module.ts:
-----------------------------------
declare var require: any;
export function highchartsFactory() {
  return require('highcharts');
}
@NgModule({
  declarations: [
    AppComponent,
    StackedChartCommit,
    StackedChartBug,
    HeatMapChart
  ],
  imports: [
    BrowserModule,
    ChartModule
  ],
  providers: [{
    provide: HighchartsStatic,
    useFactory: highchartsFactory
  },],
  bootstrap: [AppComponent]
})
-----------------------------------
The Heat Map chart is show error:
Highcharts Error #17
The requested series type does not exist
This error happens when you are setting chart.type or series.type to a series type that isn't defined in Highcharts. A typical reason may be that your are missing the extension file where the series type is defined, for example in order to run an arearange series you need to load the highcharts-more.js file.

Please help me to correct it, I'm a fresher angular :(
Thanks so much

**Comment by tungphien** [comment]
Fixed: 
export function highchartsFactory() {
  var Highcharts = require('highcharts');
  var Heatmap = require('highcharts/modules/heatmap');
  Heatmap(Highcharts);
  return Highcharts;
}

**Comment by ericuldall** [comment]
For anyone else that comes across this issue and doesn't have access to `require`, the following worked for me:

```
import * as highcharts from 'highcharts';
import * as highchartsStock from 'highcharts/modules/stock';
highchartsStock(highcharts);
```
Then just include `ChartModule.forRoot(highcharts)` in your imports.

**Comment by rkdhanyakula** [comment]
Its worked for me too.
```
import {chart} from 'highcharts';
import * as Highcharts from 'highcharts';
import * as HighchartsMore from 'highcharts-more';
HighchartsMore(Highcharts);
```

**Comment by lorrainelv** [comment]
> Its worked for me too.
> 
> ```
> import {chart} from 'highcharts';
> import * as Highcharts from 'highcharts';
> import * as HighchartsMore from 'highcharts-more';
> HighchartsMore(Highcharts);
> ```

it worked for me !

**Comment by binarycat0** [comment]
> Its worked for me too.
> 
> ```
> import {chart} from 'highcharts';
> import * as Highcharts from 'highcharts';
> import * as HighchartsMore from 'highcharts-more';
> HighchartsMore(Highcharts);
> ```

or like this

```
import Highcharts from 'highcharts'
import HighchartsReact from 'highcharts-react-official'
import * as HighchartsMore from 'highcharts/highcharts-more'

//magic
HighchartsMore(Highcharts);
```

**Comment by lorrainelv** [comment]
Thanks a lot.

arakhmatulin <notifications@github.com> 于2018年12月30日周日 上午6:10写道：
