### ISSUE TITLE
[ADVISE] Scale charts based on container 

### ISSUE THREAD

**Issue by maxtuzz** [gevgeny/angular2-highcharts#23]
Hi, 

Love the wrapper. Very simple to get up and working. 

I was wondering if you had any advise on the 'Angular 2' way towards scaling a chart based on a parent container. After some googling, the recommended way is to add something like 

`<div id="container"`

... and in my options object something along the lines of: 

```
chart: {
             renderTo: 'container'
}
```

But this doesn't seem very 'Angular 2' . Is there a recommended method, using this directive, that you would advise me to use? 

Furthermore I was wondering if you had advise towards a chart being scaled as its parent container is scaled. I'm rendering charts inside an [angular2 grid directive](https://github.com/BTMorton/angular2-grid). This enables me to move around and scale the containers holding my charts. 

![image](https://cloud.githubusercontent.com/assets/6403172/15496484/8c8a0d98-21e9-11e6-8e0b-56fbe7c0be27.png)

Unfortunately the charts don't actually scale alongside the containers until I resize the window itself. Once the window itself is resized it will snap to fill the white area below. Bare in mind this only works when I have the `rendorTo: 'container'` enabled. 
![image](https://cloud.githubusercontent.com/assets/6403172/15496515/c12e0f36-21e9-11e6-80b3-8746931ca52d.png)

I've tried a few hacks here and there to try bind the redraw method of highcharts to my containers resize() event but have been unsuccessful. Advise here would be appreciated too. 

Cheers,
Max

**Comment by gevgeny** [comment]
Could you plz provide some jsfiddle/plunker with problematic case and expected behaviour ?

**Comment by maxtuzz** [comment]
Hi sorry for late reply. 

This has been abandoned as an alternative was found. Thanks for your help.

**Comment by capcar** [comment]
Hi @maxtuzz ,
I am using angular2-grid with angular2-highcharts and I have the same problem: the charts don't actually scale alongside the containers until I resize the window itself. Once the window itself is resized it will snap to fill the white area below.
What did you do to resolve this problem? Can you help me?
Thanks
