### ISSUE TITLE
TS build error dynamic interaction with chart object 

### ISSUE THREAD

**Issue by peterwiebe** [gevgeny/angular2-highcharts#24]
I followed the example given on the README but I am getting compiler errors (in Visual Studio Code) saying that series[0] does not exist on the chart object ==> `this.chart.series[0]` gives me an error line under series.

What do I do to make it ignore this problem since it should be resolved at run time?

I should note that unlike the example given, I have my template code in a separate file whereas the demo has the template code in the same file as the component code.

When I play with the plnkr demo I notice that if I `console.log(this.chart);` I get undefined but when I `console.log(this.chart);` inside the `setInterval()` it gives me the chart object with all of its values.

My project is using Angular version rc.1

**Comment by peterwiebe** [comment]
I see the dynamic interaction now. Sorry!

**Comment by peterwiebe** [comment]
I hacked the problem by initializing chart as

```
chart = {
   series: []
}
```

instead of:

```
chart: Object;
```

then the error was resolved.

**Comment by gevgeny** [comment]
so issue can be closed ?

**Comment by peterwiebe** [comment]
I suppose it could. You may want to note on the README about this possible need for a workaround.
