### ISSUE TITLE
custom tooltip formatter

### ISSUE THREAD

**Issue by LithMage** [gevgeny/angular2-highcharts#26]
Hi,

i am trying to figure out the way to add custom tooltip formatter to the chart but if i am using typescript i cant access http://api.highcharts.com/highcharts#tooltip.formatter objects that 'this' poits to. while using plain JavaScript it works http://plnkr.co/edit/VkhPpxKlRtHKEyg2t5TS?p=preview (in maint.ts i added custom formatter).

it might be a stupid question, but i would appreciate the help :) or should i just use plain JavaScript and dont think about it?

**Comment by gevgeny** [comment]
Hmm. Looks like it is question for created of the highcharts typings. May be this can help https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts#L5237.

**Comment by LithMage** [comment]
thanks :) will try ask at typings git

**Comment by gevgeny** [comment]
And to isolate the problem you can try to code an example with only Highcharts and typings

**Comment by LithMage** [comment]
So it seems its intended that way
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9533#issuecomment-223505703

**Comment by gevgeny** [comment]
Indeed. Thanks for investigation.
