### ISSUE TITLE
Support for bullet type chart missing

### ISSUE THREAD

**Issue by jnbastoky** [gevgeny/angular2-highcharts#261]
The Bullet chart type is not supported.

https://www.highcharts.com/docs/chart-and-series-types/bullet-chart

**Comment by Jrubzjeknf** [comment]
Bullet chart type isn't part of the standard library, it's a separate module.

`import * as bullet from 'highcharts/js/modules/bullet';`

**Comment by jnbastoky** [comment]
bullet isn't in that module directory.

**Comment by Jrubzjeknf** [comment]
Did you get the latest version of the highcharts npm package?

**Comment by jnbastoky** [comment]
Thank you for the help @Jrubzjeknf. My highcharts package did need to be upgraded.

I probably should have consulted the highcharts documentation to begin with: [https://www.npmjs.com/package/highcharts#typescript](https://www.npmjs.com/package/highcharts#typescript)

```
// Load the exporting module.
import * as Bullet from 'highcharts/modules/bullet';
// Initialize exporting module.
Bullet(Highcharts);
```

**Comment by jnbastoky** [comment]
Or this method works now that I actually have the module installed per the angular2-highcharts [README](https://github.com/gevgeny/angular2-highcharts#add-highcharts-modules).

```
...
@NgModule({
    ...
    imports: [
      BrowserModule, 
      ChartModule.forRoot(
        require('highcharts'),
        require('highcharts/modules/bullet')
      )
    ],
})
```

**Comment by JeremyLopez** [comment]
I just installed the latest version `^0.5.5` and I don't have the bullet chart in the folder?  What could I be doing wrong?
