### ISSUE TITLE
Directive not updating the chart view if the chart options are updated from a http or timeout call

### ISSUE THREAD

**Issue by CristyTarantino** [gevgeny/angular2-highcharts#27]
Hi,

I have created a `plnkr` example http://plnkr.co/edit/JRvp68r9PpPTpx3Tj1tA?p=info.

I am trying to refresh the chart view when the chart options get updated through a rest call that I am faking with a setTimeout for simplicity.

In the app.component the is a method called _renderChart.

The chart does refresh if you uncomment the `NO REST CALL` code where the chart options get updated without a faked rest call.

In a setTimeout the chart fails to update the view.

This Angular 2 example shows that faking the rest call with setInterval successfully updates the view http://plnkr.co/edit/wEmO8R45p8mwwxqN7vRJ.

I don't know if it's a bug, but I would really appreciate if you could help/advice.

Thank you for any help.

**Comment by LithMage** [comment]
http://plnkr.co/edit/j8ykIE?p=preview modified yours code a bit. Not sure why but you need that Object.assign only once (otherwise no yellow point numbers, i guess something to do with how you implemented chart options). later on you just assign new series

**Comment by CristyTarantino** [comment]
Hi, thanks for your helps. The reason why I was not assigning a new series is because I wanted to keep the base options and update them by changing series data, markers colours and some others properties dynamically. So by assigning a new series I loose the base properties.

Your example, though, made me think at why in http://plnkr.co/edit/wEmO8R45p8mwwxqN7vRJ the directive was updating and in my example it was not. 
Well elementary now that I think about it: in the working example we are assigning a string which is primitive type and is assigned by value. In my example we are assigning an object which is passed by reference. So in order to have my example working I need to do a deep copy of the base object and re-assign to itself with the merged properties. 
http://plnkr.co/edit/JRvp68r9PpPTpx3Tj1tA?p=preview

Thank you so much for your help.

**Comment by gevgeny** [comment]
As soon as you initializes your chart all your further changes are dynamic and you need to use Highcharts API for the interaction with chart. Think it is time to add this to FAQ ;)

BTW here is you example http://plnkr.co/edit/Iv058gTGtHlq4gAFnzsA?p=preview

**Comment by gevgeny** [comment]
See [FAQ](https://github.com/gevgeny/angular2-highcharts/blob/master/README.md#why-dont-my-series-options-title-and-etc-update-) for more detailed explanation
