### ISSUE TITLE
boxplot type of chart does not initiate

### ISSUE THREAD

**Issue by slushnys** [gevgeny/angular2-highcharts#28]
Hello Eugene,

I've transformed your files to work with Angular2-beta.16 however the boxplot doesn't work giving me error 17, which means series or chart type is not defined. Maybe you could provide me with a working example?

Thanks in advance,
Regards

**Comment by gevgeny** [comment]
If you want to downgrade the lib you can try old releases https://github.com/gevgeny/angular2-highcharts/releases

**Comment by slushnys** [comment]
Still - how do you make a boxplot work?
I always get "ORIGINAL EXCEPTION: Error: Highcharts error #17: www.highcharts.com/errors/17"
Full error:
`Error: EXCEPTION: Error in dev/process/templates/detail.template.html:40:15
ORIGINAL EXCEPTION: Error: Highcharts error #17: www.highcharts.com/errors/17
ORIGINAL STACKTRACE:
ga@http://localhost:3000/node_modules/highcharts/highstock.js:8:256
Ba.prototype.initSeries@http://localhost:3000/node_modules/highcharts/highstock.js:215:242
Ba.prototype.firstRender/<@http://localhost:3000/node_modules/highcharts/highstock.js:237:105
Call@http://localhost:3000/node_modules/es6-shim/es6-shim.min.js:10:4624
forEach@http://localhost:3000/node_modules/es6-shim/es6-shim.min.js:10:19954
o@http://localhost:3000/node_modules/highcharts/highstock.js:26:312
Ba.prototype.firstRender@http://localhost:3000/node_modules/highcharts/highstock.js:237:78
Ba.prototype.init@http://localhost:3000/node_modules/highcharts/highstock.js:215:133
@http://localhost:3000/node_modules/highcharts/highstock.js:403:375
B.wrap/a[b]@http://localhost:3000/node_modules/highcharts/highstock.js:22:319
@http://localhost:3000/node_modu`

**Comment by gevgeny** [comment]
Provide live example plz

**Comment by slushnys** [comment]
http://plnkr.co/edit/y0J8EuXWS7VzUfGzjTXc?p=preview when i change the options, it does not work. I've been struggling for so long now, give me a way out please

**Comment by gevgeny** [comment]
You have not added appropriate module. plz looks at the Highcharts documentation then appropriate section of the README

**Comment by slushnys** [comment]
https://github.com/gevgeny/angular2-highcharts/issues/21 issue had a similar problem, I have followed this guys comments with implementing require('../../highcharts/highcharts-more.js')(Highcharts); into Highcharts.js

**Comment by gevgeny** [comment]
did you try this https://github.com/gevgeny/angular2-highcharts#using-highchart-modules ?

**Comment by slushnys** [comment]
First I did not understand how this works, maybe a better explanation could be made. Moreover it's not very related to boxplot type of chart, is it? Would you mind trying to make a boxplot type implementation with original 'options' configuration from highcharts yourself and tell me how it goes.

**Comment by gevgeny** [comment]
> First I did not understand how this works, maybe a better explanation could be made. 

This is not my invention, this magic [comes from Highcharts](http://www.highcharts.com/docs/getting-started/install-from-npm).

> Moreover it's not very related to boxplot type of chart, is it?

Using boxplot type of charts requires higcharts-more module, isn't it ?

**Comment by slushnys** [comment]
True, apparently I did not understood the module usage, my bad. It works great now also with: 

> import Highmore from '../../node_modules/highcharts/highcharts-more.js';

 Sorry for wasting your precious time. Spent too much time on this one and got annoyed...

**Comment by gevgeny** [comment]
No problem ;)

**Comment by mislitzer1991** [comment]
Hi, I want to use the bubble chart. My code in the top of my .ts file for the Highcharts looks like this **import {CHART_DIRECTIVES} from 'angular2-highcharts';**
This works perfectly with line and pie charts, but not with the bubble. I'm always getting this error: **ORIGINAL EXCEPTION: Error: Highcharts error #17: www.highcharts.com/errors/17**

I tried to use the highcharts-more module like in your description (https://www.npmjs.com/package/angular2-highcharts#using-highchart-modules), but it's not working

**Comment by gevgeny** [comment]
Did you plugged in appropriate highcharts module ?

**Comment by mislitzer1991** [comment]
Yes I have plugged in the highcharts-more module: *_import Highmore from 'highcharts/highcharts-more';  *_

**Comment by gevgeny** [comment]
could you provide live example ?

**Comment by mislitzer1991** [comment]
Thats my imported components on the top of the page, which module now i need to get the bubble chart running. I tried the highcharts-more example from zslusnys above but it's not working. I think my error is only in the imported dependencies?

import {Component} from '@angular/core';
import {Http, Response} from '@angular/http';
import {Observable} from 'rxjs/Rx';
import 'rxjs/add/operator/map';
import {NavController, NavParams} from 'ionic-angular';
import {CHART_DIRECTIVES} from 'angular2-highcharts';

**Comment by gevgeny** [comment]
Works for me http://plnkr.co/edit/GtOmvbnO22tI1wPoqZJa?p=preview

**Comment by mislitzer1991** [comment]
Hi thank you for your response. I'm not sure where my mistake is. I've seen in your example that you provide an systemjs.config.js file. Did I need this one or not? 

I'm always getting this error when compiling: Error TS2307: Cannot find module 'highcharts/highcharts-more'
