### ISSUE TITLE
Chart not responsive in my App

### ISSUE THREAD

**Issue by Simsal** [gevgeny/angular2-highcharts#29]
Hey,

i try to use it in my ionic2 App.
Graph is showing but unfortunatly, it is not resizing based on screen size.
Screenshot: 
![image](https://cloud.githubusercontent.com/assets/7790706/15961709/7d1ed6e8-2f06-11e6-963d-459bca7afb1e.png)

Any advise?
Greetings

**Comment by gevgeny** [comment]
Actually no ideas since have not worked with ionic2. Did you try ouse the same options and layout in the desktop browser ?

**Comment by Simsal** [comment]
It is a Screenshot, taken in Chrome with mobile device emulator.

Just tried your demo plunkr and everything is working smoothly. 

It is also responsive in my app now, but only after rotating the screen.

Greetings
