### ISSUE TITLE
Responsive chart

### ISSUE THREAD

**Issue by santclear** [gevgeny/angular2-highcharts#30]
Hi, can you answer me a question? How do you make the width of responsive chart? I've tried to set the css to width = 100% in Highcharts-container class and svg component, but it did not work. I've tried also set a class on the chart component with width = 100% and did not work: - /
Note: Of the two ways I tried, the graph to be responsive, but a part of the chart figure is cut right.

**Comment by gevgeny** [comment]
See the first demo in the readme

**Comment by santclear** [comment]
Very good, chart display block;-) Thank you. In Ionic 2 there is a bug. This command only works after resizing the browser window.

**Comment by santclear** [comment]
Solve, I put the piece of code in the ngAfterViewInit() method.

**Comment by oliviercherrier** [comment]
Thank you. Solved my issue too :)

**Comment by oliviercherrier** [comment]
@santclear Hello, can you give me the piece of code you put in ngAfterViewInit() ?

Thank you.

**Comment by santclear** [comment]
@oliviercherrier 
I used the example of gevgeny, you can check by going to the 'code' tab. Instead of writing the code in the constructor, as shown by him, you must put in ngAfterViewInit method.

**Comment by oliviercherrier** [comment]
@santclear 

Thank you for your help. I tried during 2 hours to fix this problem by adding the 'this.options = {...}' to the 'ngAfterViewInit' method... without success.

Thanks to this article: "http://4dev.tech/2016/05/angular2-tutorial-creating-awesome-animated-charts-with-highcharts/", I try to remove the ion-content balise I put arround the <chart> tag and.... it works: chart size is correct from the first load of the window... Even if the constructor code is not put into the 'ngAfterViewInit' method.

Thank you for your help and hoping it could help other developers...

**Comment by oliviercherrier** [comment]
[Issue opened on Highcharts.](https://github.com/driftyco/ionic/issues/7823)

**Comment by santclear** [comment]
@oliviercherrier Thanks for sharing.
I'll make a note. You do not need to run JQuery on Highcharts. Not even the angular2-Highcharts under Angular 2 and Ionic 2 apps.
To run the pure Highcharts, follow these instructions:
1. Download as shown in: http://www.highcharts.com/docs/getting-started/install-from-npm;
2. On the import of your code, import as shown in step 1 and import too:
`import {Component, ViewChild, ElementRef} from '@angular/core';`
3. In your component create a global attribute just below the class definition: 
`@ViewChild ( 'myChart') canvas: ElementRef;`
4. In a method or constructor, create your Highcharts code inside:

```
var chart = hcharts.chart (this.canvas.nativeElement {
    chart: {
        zoomType: 'x',
        events: {
            load: function () {
                var self = this;
                setTimeout (function () {
                    self.reflow ();
                }, 100)
            }
        }
    },
    series: [{
        time: [1, 3, 2, 4]
    }]
});
```

4.1. Note, that I used the resize strategy shown in: http://plnkr.co/edit/R6W6IKXhkxIB9RjLwyEN?p=preview | look for home.ts file
5. Make a binding of your Highcharts code with a view in your HTML file: 
`<div #myChart> </ div>`

**Comment by oliviercherrier** [comment]
@santclear Thank you for your recommendation, I will implement them in the coming days.

Before it, I am  trying to execute the reflow() function into a callback executed once container is visible: I tried `ionViewDidEnter` without success on my laptop (see http://plnkr.co/edit/atsoDMAmsalGTUJD8nF7?p=preview). I just asked Ionic 2 team to know the callback to use.

I hope to find this callback to avoid use of an arbitrary timeout value.

**Comment by oliviercherrier** [comment]
ionViewDidEnter is the good callback to use. Ionic have to fix a bug  to launch this callback only since the entire page is rendred

**Comment by oliviercherrier** [comment]
Hello @santclear 

I just implemented your recommendations with success :-). 

But I am not satisfied by my implementation of `reflow()` in `ionViewDidEnter` lifecycle callback (as preconized by Ionic): I don't kwow the good way to access to the chart previously rendered in `renderChart()`.

 Can you advise me on how to share this kind of object into an Angular 2 Component ?

Thank you for your help,

Olivier.

**Comment by oliviercherrier** [comment]
@santclear 

On my first inspiration, I implement it: http://plnkr.co/edit/p0SDqfg6L29RFgCxcmYB?p=preview. But it does not work...

**Comment by santclear** [comment]
Hello @oliviercherrier
I created the application that can be accessed at the following link, to be used as an example: https://github.com/santclear/sample-highcharts-ionic2

**Comment by kaysonio** [comment]
Have been banging my head against this brick wall all day - problem solved thanks to the above. Thank you :)

**Comment by oliviercherrier** [comment]
Hello @santclear 

Sorry for my late reply, I was climbing the mountain, with a very limited access to Internet ;-)

Thank you for your application. My question is about: how to share the "chart" variable in the scope of the `HomePage` class and in accordance to Angular 2 principles ? For example, how to get chart object in the `ionViewDidEnter` callback provided by Ionic 2 ? 

I success to share it in this example: http://plnkr.co/edit/p0SDqfg6L29RFgCxcmYB?p=preview, but I think that it is not the good way to do...

Thank you for your help

**Comment by oliviercherrier** [comment]
Fixed in http://plnkr.co/edit/p0SDqfg6L29RFgCxcmYB?p=preview

**Comment by akki10** [comment]
How to make this work for Angular 2 v2.2.3 ?

**Comment by wustdong** [comment]
This works for me ( angular 4):
Add the HostListener inside the @Component()-decorator. Then put redraw() function call in the host-metadata-property after constructor()  like so:

```
 @ViewChild('chart')
  private chartObj: ChartComponent;

 constructor(){
 }

  @HostListener('window:resize', ['$event'])
  onResize(event) {
    if (this.chartOrg) {
      this.chartOrg.reflow();  
    }
  }
```

```
  _saveInstance(chart) {
    this.chartOrg = chart;
  }
```
```
  <chart #chart [type]="chartStandard" [options]="options" (load)="_saveInstance($event.context)"></chart>
```
reference:
[Angular window resize event](https://stackoverflow.com/questions/35527456/angular-window-resize-event)
[](url)
