### ISSUE TITLE
upgrade to Angular2 RC 2

### ISSUE THREAD

**Issue by ywmail** [gevgeny/angular2-highcharts#31]
could you please upgrate to angular 2 rc 2 and publish to the npm repository?

**Comment by gevgeny** [comment]
Will do later. Or you can PR ;)

**Comment by ywmail** [comment]
I'm working behind a corporate proxy, unfortunately I can't upload files.
So maybe I can do the PR via another internet connection...

**Comment by davidw** [comment]
As someone new to Angular, what are the key differences or things to focus on?

**Comment by gevgeny** [comment]
updated to rc-3

**Comment by davidw** [comment]
Excellent - thanks!
