### ISSUE TITLE
[Request] Highstock Events - Access to xAxis.events.setExtremes event

### ISSUE THREAD

**Issue by djrr94** [gevgeny/angular2-highcharts#32]
Hello, I'm using your chart directives in our project and I love it so much.

I'm using Highstocks and I need to know when user changes range of the chart and put these extremes in two variables (like in your example). I've tried your example with (selection) event emitter, but it doesn't work with navigator (editing range and panning) and range selector buttons (1M, 3M, YTD, ALL). It works only with editing the area in the chart (zooming and panning). That's probably because this event is made for Highcharts, not Highstocks.

I wanted to ask if there is (or will be) any way to access the xAxis.events.setExtremes event. I tried it through console.log and it worked like a charm, but I cannot assign these values to angular2's model variables.

I also thought that would be a nice thing to present in your examples, for users who need to use highstocks.

I appreciate your great work, thank you in advance.

**//EDIT**
Just for completation, you can see desired behavior [here](http://plnkr.co/edit/OrXD6VSTJaX9vZr8rrL4?p=preview). Just check the console log.

**Comment by gevgeny** [comment]
I really cannot understand the question.

**Comment by gevgeny** [comment]
If you can fetch values in the event handler why you cannot assign them to a variable ?

**Comment by djrr94** [comment]
Sorry, my description maybe weren't so clear.

Maybe I'm doing something wrong, but in [this updated plunk](http://plnkr.co/edit/OrXD6VSTJaX9vZr8rrL4?p=preview) you can see that console logging with these variables works okay, but assigning these values to this.from and this.to model variables doesn't work.

`xAxis: {
                    events: {
                        setExtremes: function (e) {
                            this.from = Highcharts.dateFormat(null, e.min); // Doesn't work
                            this.to = Highcharts.dateFormat(null, e.max); // Doesn't work
                            console.log('min: ' + Highcharts.dateFormat(null, e.min) + ' max: ' + Highcharts.dateFormat(null, e.max)); // Works
                        }
                    }
                }`

So I thought the correct way doing this is through your event emitters like (selection) in template, or I can really miss something.

**Comment by gevgeny** [comment]
You are not changing properties of your component in your fiddle. see http://plnkr.co/edit/IXmgt9CcR15B3WbUizKr?p=preview

**Comment by djrr94** [comment]
Aww, I though I must miss something, thank you so much!

**Comment by gevgeny** [comment]
Yes, you did. How function context works in JS ;) https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/this

**Comment by arjun289** [comment]
I am trying to access the rangeSelector button event inside my component using the (selection). But I am not able to do so if the button is pressed. http://plnkr.co/edit/OwcqjORHCB9pZHBrt4cm?p=preview. Do I need to export something from the event?
