### ISSUE TITLE
confict with orignal highcharts type definition file, and typings has upgraded to 1.3.0

### ISSUE THREAD

**Issue by ywmail** [gevgeny/angular2-highcharts#33]
Hi, maybe the `typings` directory in the root `angular2-highcharts` should be removed?

**Comment by gevgeny** [comment]
What do you mean by orignal highcharts type definition file ?

**Comment by ywmail** [comment]
angular2-highcharts is depended on highcharts, so I install highcharts `npm install highcharts --save`, and then I also install it's type definition file by `typings install -g highcharts --save`. I thiink the `root\typings\globals\highcharts\index.d.ts` has conflict with angular2-highcharts, because angular2-highcharts also includes the highcharts type definition file.

**Comment by gevgeny** [comment]
You no need to instal highcharts nor it's typings. As soon as you add angular2-highcharts to list of the dependencies all it's dependencies will be installed automatically.

**Comment by ywmail** [comment]
Thank you, I think I can launch my web application now. :)
