### ISSUE TITLE
how to update the chart's data? 

### ISSUE THREAD

**Issue by steveburkett** [gevgeny/angular2-highcharts#36]
When i use this w/ highcharts...i pull the data in ngOnInit (1 to N series of data) thru an API and set the options.

I have a form above my chart to set data variables...and when submitted, i get new data for the chart.  The new data could again, be 1 to N series of data. 

I need a way to update the current chart (gracefully).  How do i reset (all) the data at once, or update to new options (which includes new series data, new xAxis categories).  

Here's a simplified example (click me button) of what i'm trying to do:
http://plnkr.co/edit/uEaaTcfciT9OlUtwJWuC?p=preview

**Comment by gevgeny** [comment]
See the [FAQ](https://github.com/gevgeny/angular2-highcharts#faq) section

**Comment by LithMage** [comment]
you can remove all series in one go with this

```
let i = (chart.series.length > 0) ? chart.series.length : 0;
      while (i--) {
        chart.series[i].remove(false);
      }
```

other than that your doing it right (that is using Highcharts API) just if there is a lot of changes it might be easier to destroy chart ant create it anew.
