### ISSUE TITLE
series: ChartSeriesComponent difficult to access

### ISSUE THREAD

**Issue by davidw** [gevgeny/angular2-highcharts#37]
Hi,

I'm pretty new to TypeScript, so this may well be something I don't understand correctly, but I've hit a bit of a wall.

I want to do this:

```
for (var series of this.chart.series) {
            series.remove();
}
```

But I get

`Type 'ChartSeriesComponent' is not an array type or a string type`

I would have expected to see something more like

`series: ChartSeriesComponent[]` in `ChartComponent.d.ts`.

Thoughts?  Thank you!

**Comment by LithMage** [comment]
Well i am running something similar

```
removeAllSeries(chart: HighchartsChartObject) {
    let i = chart.series.length;
    while (i--) {
      chart.series[i].remove();
    }
  }
```

and i have no problems with it.

Did you save chart instance to this.chart?

**Comment by gevgeny** [comment]
I tried to run 

```
for (var series of this.chart.series) {
            series.remove();
}
```

with Webpack + ts-loader and it compiles and works fine

**Comment by gevgeny** [comment]
Closing due to silence
