### ISSUE TITLE
Cannot add series when zoomed in

### ISSUE THREAD

**Issue by rachelmad** [gevgeny/angular2-highcharts#40]
If you create a line chart with data on it, zoom in, then try to delete the lines and axes, the following occurs.

Calling:
`this.chart.yAxis[0].remove()`

Throws the following error:
TypeError: Cannot read property 'pos' of undefined

This works flawlessly when the chart is not zoomed in.

**Comment by gevgeny** [comment]
How is it related to angular2-highcharts? Looks like it is Highcharts specific issue.

**Comment by rachelmad** [comment]
I tried doing it on jsfiddle using regular highcharts and it worked there.

**Comment by LithMage** [comment]
Adding removing series works without any problems. Just tested with removing xAxis and it also works no problem
http://plnkr.co/edit/VkhPpxKlRtHKEyg2t5TS

Edit: yAxis been removed with no problem either.

**Comment by gevgeny** [comment]
@rachelmad Could you somehow share you code ?

**Comment by AndrewKralovec** [comment]
Solution?
