### ISSUE TITLE
Is drilldown working?

### ISSUE THREAD

**Issue by verbeeckjan** [gevgeny/angular2-highcharts#42]
Hello, first of all thanks for creating this library.

I was trying to recreate an example from the highcharts website which includes drilldown. But it seems that drilldown isn't working. I've loaded both the data and drilldown module and the data module from the regular highcharts npm module.

This is the example:
[http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-drilldown/](url)

**Comment by gevgeny** [comment]
It should work. Just read the readme closely to understand how to plug highcharts modules. Elsewhere post some live example with problematic code.

**Comment by verbeeckjan** [comment]
The drilldown is included in the highcharts npm module so it doesn't seem to work the same as the  example. There seems to be no d.ts file for the highcharts modules.

**Comment by gevgeny** [comment]
Did you check this repo's readme https://github.com/gevgeny/angular2-highcharts#using-highchart-modules ?

**Comment by verbeeckjan** [comment]
Yes, and I looked at the demo. It seems like the demo is using systemJS (never used this before) to make the highcharts-3d.src.js file load like an ES6 module.

**Comment by gevgeny** [comment]
Yes, but it is up to you which bundler to use. Here is your case http://plnkr.co/edit/puZRZsl8JwBDMHT6Z8rj?p=preview

**Comment by verbeeckjan** [comment]
Okay, thank you very much for the example. It seems indeed to be related to the bundler. Too bad that Ionic doesn't include a better bundler out of the box. I'll try it using SystemJS

**Comment by gevgeny** [comment]
you are welcome

**Comment by kogen00** [comment]
Sorry to dig this out but... could you give an example how drill down is used with the latest version of Angular2 (Tested it with Angular 2.4 and it failed).
I'm a bit lost cause after importing the Chart-Module it still does not know how to drilldown.
Thanks.

**Comment by martynbiz** [comment]
As the previous poster wrote, is it possible to see an example of code with drilldown? I'm also having problems getting the drilldown to work, but the same config works with Highcharts JS library on my other (non-NG) websites. Here's what I'm passing:

```javascript
export class CategoriesChartComponent implements OnInit {

    ngOnInit() { }

    constructor() {
        this.options = {
            "chart": {
                "plotBackgroundColor": null,
                "plotBorderWidth": null,
                "plotShadow": false,
                "type": 'pie'
            },
            "title": {
        		"text": "Expenses"
        	},
            "tooltip": {
        		"headerFormat": "<span style=\"font-size:11px\">{series.name}<\/span><br>",
        		"pointFormat": "<span style=\"color:{point.color}\">{point.name}<\/span>: <b>{point.y:&pound;%01.2f}<\/b> of total<br\/>"
        	},
            "plotOptions": {
        		"pie": {
        			"allowPointSelect": true,
        			"cursor": "pointer",
        			"dataLabels": {
        				"enabled": false
        			},
        			"showInLegend": true
        		}
        	},
            "series": [{
        		"name": "Groups",
        		"colorByPoint": true,
        		"data": [{
        			"name": "Leisure",
        			"y": 1038.81,
        			"drilldown": 4
        		}

                //...
                ]
        	}],
        	"drilldown": {
        		"series": [{
        			"name": "Leisure",
        			"id": 4,
        			"data": [
        				["Holidays", 61.3],
        				["Gardening", 78.66],

                        //...
        			]
        		}, 
                
                //...
                ]
        	}
        };
    }
    options: Object;

}
```
```

**Comment by Prashanth-Thomas** [comment]
@kogen00  **This should be your code in the AppModule.ts file. Your Drilldowns should work, but it might still throw an error on the console.**

import { NgModule } from '@angular/core';
import { HighchartsStatic } from 'angular2-highcharts/dist/HighchartsService';
import {CommonModule} from "@angular/common";
import { DrilldownComponent } from './drilldown/drilldown.component';
import {ChartModule} from "angular2-highcharts";


export function highchartsFactory() {
  const hc = require('highcharts');
  const dd = require('highcharts/modules/drilldown');
  dd(hc);
  return hc;
}
declare var require: any;
@NgModule({
  declarations: [
  DrilldownComponent],
  imports: [
    CommonModule,
    ChartModule
  ],
  providers: [{
    provide: HighchartsStatic,
    useFactory: highchartsFactory
  }],
  bootstrap: [DrilldownComponent],
  exports:[DrilldownComponent]
})
export class AppModule { }

**Comment by mohammedalidriss** [comment]
import * as  Highcharts from 'highcharts/highcharts.src';
import 'highcharts/adapters/standalone-framework.src';
import * as  Drilldown from 'highcharts/modules/drilldown.src';

.........
 constructor() {
    Drilldown(Highcharts);
  }
........

**Comment by khraibani** [comment]
For anyone facing this issue and using Webpack.
const Highcharts = require('highcharts');
const Drilldown = require('highcharts/modules/drilldown')(Highcharts); // tslint:disable-line
Drilldown;

**Comment by manhar-developer** [comment]
I am still facing this issue. Unable to use drilldown with Angular 4

Refer : https://stackoverflow.com/questions/49690245/drill-down-highcharts-not-working-in-angular-5

**Comment by EagleDangar** [comment]
Can someone provide me any working solution of this example .
please.
