### ISSUE TITLE
Changing the options cause the page to scroll up

### ISSUE THREAD

**Issue by Ghyath-Serhal** [gevgeny/angular2-highcharts#43]
I am trying to implement the drill down functionality, But I am facing a problem when changing the options variable, the web page scrolls up.
On the point click event, I am getting new data from the server and rebuilding the options variable. The web page scrolls up.

**Comment by gevgeny** [comment]
Could you plz provide live example ?

**Comment by Ghyath-Serhal** [comment]
Please take a look at the below Plunker, it contains the issue that i am talking about.
Scroll down, and click on the chart. the data of the chart will change but the page will automatically scroll up.

http://plnkr.co/edit/UQxyJfQhEbzvWPAQNCHL?p=preview

**Comment by gevgeny** [comment]
Hm, are you sure the issue is caused by angular2-highcharts ?

**Comment by Ghyath-Serhal** [comment]
Honestly I am not sure, i am still trying to figure out. But I tried the same scenario using HighCharts, it is working normally.
I realized that when changing the options variable, this behavior appears.

**Comment by LithMage** [comment]
You might want to check out this example about drilldown in Highcharts
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/async/

**Comment by Ghyath-Serhal** [comment]
I put the chart in a div with a fixed height. now it is working. Hence it is not an issue caused by angular2-highcharts.
Thank you for your help

**Comment by gevgeny** [comment]
No problem
