### ISSUE TITLE
NoData module

### ISSUE THREAD

**Issue by pantonis** [gevgeny/angular2-highcharts#47]
I am trying to import no-data module. I have read the readme file but still haven't manage to make it work.

I have the following in the systemjs.config.js

```
        'highcharts/noData': '/js/no-data-to-display.src.js'
```

and then in the .ts the following

```
import {NoData}             from 'highcharts/noData';
```

and I get cannot find module  'highcharts/noData';

Do you have any idea what am I doing wrong?

**Comment by gevgeny** [comment]
check you path to the highcharts repo 
http://plnkr.co/edit/XafHn6tWl02eyZzPn1Sd?p=preview

**Comment by pantonis** [comment]
I followed your plnkr example and still get the same error

**Comment by gevgeny** [comment]
works fine with Chrome 52

**Comment by pantonis** [comment]
I meant in my code. cannot find module 'highcharts/highcharts-3d';
