### ISSUE TITLE
Property 'series' does not exist on type 'Object'

### ISSUE THREAD

**Issue by ceolinwill** [gevgeny/angular2-highcharts#48]
I'm following [this example](http://plnkr.co/edit/OQSFSKisIIWAH0megy4d?p=preview) to create a dynamic chart but I'm having the error above.

Here's what I'm trying to do:

```
this.service
  .getData()
    .then(res => {
      this.chart.series[0].setData(this.chartData(res));
    })
    .catch(error => this.error = error);
```

Any hints on what I'm missing here?

**Comment by gevgeny** [comment]
Plz provide live demo

**Comment by ceolinwill** [comment]
Here: http://plnkr.co/edit/xmZRhTxKhV79Z9Djt6oI?p=preview

**Comment by ceolinwill** [comment]
@gevgeny I figured it out. I was calling the chart series during `onInit`. Therefore, it was loading before `chartInstance`. :P

**Comment by ceolinwill** [comment]
@gevgeny Another thing, though. I'm using `angular-cli` and, during the build, I still get that same error, so it doesn't compile.

A workaround is if I set `this.chart = chartInstance.series`. It's not a good solution, though, as I might use other options later on like `setOptions`.

I wonder what's the proper way to do that.

**Comment by elvisbegovic** [comment]
series not exit @wceolin  do you have working demo with setOptions please  ? cause I can't build

**Comment by ceolinwill** [comment]
@istiti I ended up using Highcharts natively, without any third-party libraries :P

**Comment by elvisbegovic** [comment]
@wceolin  why you close this ? error's still here no ?

**Comment by alx-andru** [comment]
Is there any progress or ideas on this? I'm using AngularCli and essentially copying the live demo provided. Complier is moaning about it. Would it help to create a plunkr with an example?

**Comment by keepscoding** [comment]
@wceolin @istiti you can try to define 
`chart;
`
instead of 
`chart: Object;`
I think Object of chart has no series property that'y error.

**Comment by alx-andru** [comment]
Declaring
`chart: any;`
worked for me.

**Comment by Tameshiwari** [comment]
Just to confirm, I  am using angular2-highcharts in an Angular 4 CLI app I created on VSCode and I first had the same issue though:
Declaring
`chart:any;`
worked it in my case. Everything runs fine. :)
BTW anyone knows how to apply Dark-Unica theme?
