### ISSUE TITLE
Add the possibility to bind the xAxis and yAxis events

### ISSUE THREAD

**Issue by serrut** [gevgeny/angular2-highcharts#49]
Currently i cannot find a way to bind events to the xAxis and yAxis (afterSetExtremes, pointInBreak, setExtremes). Specially the setExtremes event would be very useful to have.

You can bind them via the options, but then it seems that the event is executed in another context and I cannot access data of my component which is using the Highcharts component.

**Comment by gevgeny** [comment]
>  it seems that the event is executed in another context and I cannot access data of my component which is using the Highcharts component.

Not sure can understand you. Options events should work as well. May you provide some live demo ?

**Comment by serrut** [comment]
I've adjusted the plunk you made, to explain my problem: http://plnkr.co/edit/FVHCyfUbH3hmw9GALdXM?p=preview

If you take a look in the console of your browser, you will see that the _this_ object which is logged when changing the extremes, will be the X-axis of the Highcharts component, and not current component you are working in.

In the mean time I already checked out your code and implemented the events to it, in the same way you've implemented the series and point events. If you would provide me a pull request, i can check in this code. By adding this fix, i can solve my problem and access the component.

**Comment by gevgeny** [comment]
Yes. Pull request would be great. But be sure you add all the functionality, examples, tests, and update readme.

**Comment by serrut** [comment]
Pull request created: https://github.com/gevgeny/angular2-highcharts/pull/50

**Comment by fank** [comment]
@gevgeny @serrut i think this is fixed or?

**Comment by gevgeny** [comment]
yes
