### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by 4sur3** [gevgeny/angular2-highcharts#51]
Hi all

Trying to install the lib in an angular2-rc5 application I'm getting some errors:

**1) npm install angular2-highcharts --save**

**2) ...**
 node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz (**This line fails because an "Access Denied" message**)
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.3.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
...
 CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
  CXX(target) Release/obj.target/zopfli/src/png/zopflipng.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/cache.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/deflate.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/gzip_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/hash.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/katajainen.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/lz77.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/squeeze.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/tree.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/util.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zlib_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zopfli_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/zopflipng_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng_util.o
  SOLINK_MODULE(target) Release/obj.target/zopfli.node
  COPY Release/zopfli.node
...

├─┬ angular-cli@1.0.0-beta.11-webpack.2
│ ├─┬ compression-webpack-plugin@0.3.1
│ │ └─┬ node-zopfli@1.4.0 
│ │   ├── defaults@1.0.3 
│ │   └─┬ node-pre-gyp@0.6.29 
│ │     ├── npmlog@3.1.2 
│ │     ├─┬ rc@1.1.6 
│ │     │ └── ini@1.3.4 
│ │     ├── semver@5.2.0 
│ │     └─┬ tar-pack@3.1.4 
│ │       ├── fstream-ignore@1.0.5 
│ │       └── uid-number@0.0.6 
│ └─┬ less@2.7.1
│   ├── image-size@0.5.0 
│   ├─┬ promise@7.1.1 
│   │ └── asap@2.0.4 
│   └── source-map@0.5.6 
├─┬ angular2-highcharts@0.1.1 
│ └── highcharts@4.2.6 
├─┬ karma-remap-istanbul@0.2.1
│ └─┬ istanbul@0.4.4
│   └─┬ escodegen@1.8.1
│     └── source-map@0.2.0 
├─┬ protractor@3.3.0
│ └─┬ request@2.67.0
│   └─┬ http-signature@1.1.1
│     └─┬ sshpk@1.9.2
│       ├── ecc-jsbn@0.1.1 
│       ├── jodid25519@1.0.2 
│       ├── jsbn@0.1.0 
│       └── tweetnacl@0.13.3 
└── **UNMET PEER DEPENDENCY** typescript@2.0.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.

**3) I tried updating the typscript module to the latest**
tsc -v
Version 2.1.0-dev.20160817

**4) At this point there is an entry in the package.json with angular2-highcharts. But if I try o use it in my app.module file, I get an error:**

./~/angular2-highcharts/dist/index.js
Cannot find source file '../src/index.ts': Error: Can't resolve '../.../charts-test/node_modules/angular2-highcharts/dist'
 @ ./~/angular2-highcharts/index.js 4:9-32
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

Any idea ?.

Thanks in advance.

**Comment by fank** [comment]
zopfli came from angular-cli, i can confirm this issue appears sometimes.

```
├─┬ angular-cli@1.0.0-beta.11-webpack.2
│ ├─┬ compression-webpack-plugin@0.3.1
│ │ └─┬ node-zopfli@1.4.0 
```

But its not related to this repository.
