### ISSUE TITLE
Multiple y-axis broken in 0.2.1

### ISSUE THREAD

**Issue by alastrange** [gevgeny/angular2-highcharts#56]
Passing options with multiple y-axis' as an array no longer works in 0.2.1.  Debugging the code, the axis array is transformed into an object before being passed into the highcharts javascript code, and fails to iterate because of that.  It may have something to do with this update which initializes the axis' as objects.

https://github.com/gevgeny/angular2-highcharts/commit/0cfdb609f9a7669bcdf6bf2688390b67a09757b0

Example options:  http://www.highcharts.com/demo/combo-multi-axes

**Comment by dantullis** [comment]
I can confirm this as well. The following does not work:
Highcharts Error 18
The requested axis does not exist
This error happens when you set a series' xAxis or yAxis property to point to an axis that does not exist.

```
  series: [
        {
          name: 'test1',
          type: 'column',
          data: Array.from(new Array(100), (x, i) => i),
          yAxis: 1,
          tooltip: {
            valueSuffix: ' mm'
          }
        },
        {
          name: 'test2',
          type: 'line',
          data: Array.from(new Array(100), (x, i) => i + 3),
          yAxis: 2,
           tooltip: {
            valueSuffix: ' mm'
          }
        }
      ]
```

However, if you comment out `yAxis: 1,` and `yAxis: 2,` then it will work.

```
  series: [
        {
          name: 'test1',
          type: 'column',
          data: Array.from(new Array(100), (x, i) => i),
          // yAxis: 1,
          tooltip: {
            valueSuffix: ' mm'
          }
        },
        {
          name: 'test2',
          type: 'line',
          data: Array.from(new Array(100), (x, i) => i + 3),
          // yAxis: 2,
           tooltip: {
            valueSuffix: ' mm'
          }
        }
      ]
```

I would look into fixing this, but I'm still new to it. Any suggestions?

**Comment by kuvelas** [comment]
+1
Revered to 0.1.1 and yAxis works as expected

**Comment by Hemantham** [comment]
Any idea when this will be fixed or is there an workaround ?
