### ISSUE TITLE
Duplicate identifier errors

### ISSUE THREAD

**Issue by magnattic** [gevgeny/angular2-highcharts#6]
I am trying to use angular2-highcharts within a project based on [angular2-seed](https://github.com/mgechev/angular2-seed), but get the following errors when starting the application:

```
C:/Projekte/angular2-seed2/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(8,14): error TS2300: Duplicate identifier 'PropertyKey'.
C:/Projekte/angular2-seed2/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(11,5): error TS2300: Duplicate identifier 'done'.
C:/Projekte/angular2-seed2/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(12,5): error TS2300: Duplicate identifier 'value'.
C:/Projekte/angular2-seed2/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(250,5): error TS2300: Duplicate identifier 'EPSILON'.
C:/Projekte/angular2-seed2/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(285,5): error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
[...]
C:/Projekte/angular2-seed2/typings/browser/ambient/es6-shim/index.d.ts(8,14): error TS2300: Duplicate identifier 'PropertyKey'.
C:/Projekte/angular2-seed2/typings/browser/ambient/es6-shim/index.d.ts(11,5): error TS2300: Duplicate identifier 'done'.
C:/Projekte/angular2-seed2/typings/browser/ambient/es6-shim/index.d.ts(12,5): error TS2300: Duplicate identifier 'value'.
C:/Projekte/angular2-seed2/typings/browser/ambient/es6-shim/index.d.ts(250,5): error TS2300: Duplicate identifier 'EPSILON'.
C:/Projekte/angular2-seed2/typings/browser/ambient/es6-shim/index.d.ts(285,5): error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
[...]
```

The same messages show up for jasmine typings.

Steps to reproduce:
1. Checkout angular2-seed: https://github.com/mgechev/angular2-seed.git
2. Add to package.json under dependencies: `"angular2-highcharts": "^0.0.6"`
3. Add `simple.chart.ts` under `src/home/components/`:
   
   ```
   import { Component } from 'angular2/core';
       import { CHART_DIRECTIVES } from 'angular2-highcharts';
   
       @Component({
           selector: 'simple-chart-example',
           directives: [CHART_DIRECTIVES],
           template: `
               <chart [options]="options"></chart>
           `
       })
       export class SimpleChartExample {
           constructor() {
               this.options = {
                   title : { text : 'simple chart' },
                   series: [{
                       data: [29.9, 71.5, 106.4, 129.2],
                   }]
               };
           }
           options: Object;
       }
   ```
4.  Run `npm install` and `npm start`.

Any idea how to make it work?

**Comment by magnattic** [comment]
Also discussed at mgechev/angular2-seed#735, because I am not sure which of both projects is the one to fix this in.

**Comment by gevgeny** [comment]
Thanks, I tried to integrate the lib with other starter https://github.com/AngularClass/angular2-webpack-starter and it works good. Will try to run with the angular2-seed later.

**Comment by magnattic** [comment]
Here is what I think is going on: I have the type definitions for es6-shim and jasmine locally in my (seed) project in the typings folder. Because angular2-highcharts uses them as well, they are also in the `node_modules/angular2-highcharts/typings/` folder.

I told the typescript compiler to exclude the node_modules folder, but because you have the line `/// <reference path="../typings/browser.d.ts" />` in `dist/index.d.ts` (which gets imported, I guess), the exclude is ignored and the typings from angular2-highcharts are being imported and compiled as well.

According to [this article on the whole typings topic](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/):

> Using `<reference/>` is considered a bad practice.

It's only a theory based on my limited understanding, but I think the `<reference/>` in the repo is what causes the problem.

Is the reference really necessary, can't this be solved by including the typings during compile time?

**Comment by gevgeny** [comment]
Thanks for investigation. Will fix this later. you also are welcome to PL

**Comment by magnattic** [comment]
Thanks, I hope that really is the issue. I am pretty new to the typescript world, so take it with a grain of salt. ;) 

I really appreciate the work you did with this repo, can't wait to use it!

**Comment by magnattic** [comment]
FYI: I just checked out the latest commit, works perfectly for me without any errors. Thanks for the quick fix!

**Comment by gevgeny** [comment]
Great. Right now i am testing this with angular2-seed but having problem with running it even without angular2-higcharts. As soon as i run it i will publish new version

**Comment by gevgeny** [comment]
@atticae I finally could run angular2-seed but have typings errors when try to integrate angular2-highcharts:

```
[12:56:33] Starting 'build.js.dev'...
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/ChartComponent.d.ts(7,26): error TS2304: Cannot find name 'HighchartsChartObject'.
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/ChartComponent.d.ts(17,12): error TS2304: Cannot find name 'HighchartsChartObject'.
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/ChartComponent.d.ts(23,14): error TS2304: Cannot find name 'HighchartsOptions'.
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/ChartEvent.d.ts(3,14): error TS2304: Cannot find name 'HighchartsChartObject'.
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/ChartEvent.d.ts(3,38): error TS2304: Cannot find name 'HighchartsSeriesObject'.
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/ChartEvent.d.ts(3,63): error TS2304: Cannot find name 'HighchartsPointObject'.
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/ChartEvent.d.ts(3,87): error TS2304: Cannot find name 'HighchartsAxisObject'.
/Users/egluhotorenko/Dev/angular2-seed/node_modules/angular2-highcharts/dist/HighchartsService.d.ts(2,17): error TS2304: Cannot find name 'HighchartsStatic'.
[12:56:35] TypeScript: 8 semantic errors
```

Looks like Highcharts typings which stored in  node_modules/angular2-highcharts/typings are not available now. How did you solve this ?

**Comment by gevgeny** [comment]
I added reference to native Highcharts typings and published v0.0.7

**Comment by magnattic** [comment]
Hey, sorry for the late response. 

I solved this by installing the typings for highcharts to my own project. I am not sure what the correct way is for such cases. 

The current setup doesn't work for me, because when I try to build for production (npm run build.prod) I get an error because of the new triple-slash references:

> C:/Projekte/sd4/frontend/node_modules/angular2-highcharts/dist/Highcharts.d.ts(2,1): error TS6053: File 'C:/Projekte/sd4/frontend/node_modules/angular2-highcharts/typings/browser/ambient/highstock/index.d.ts' not found.

I think it's important not to have any triple slash references in the dist folder, that seems to mess things up because the compiler tries to follow them.

The only other solution I can think of is to include the typings in the project, but that might lead to other trouble with duplicate typings...

**Comment by gevgeny** [comment]
Hey. Just tried to run `npm run build.prod` and it works for me. Try to reinstall `angular2-highcharts@0.0.8`. And regarding the triple slash ref, i also don't like such solution but that is the only way to deliver the existing third-party typings. Let me know if come up any better idea.

**Comment by magnattic** [comment]
I am not sure its a good idea to "deliver" the third party typings, because as soon as two node_modules deliver the same third party typing, it will result in duplicates. The references may be necessary for building the package, but should be removed from distribution, I think. Anyway, if I use 0.0.8 and remove my own highcharts typings, it compiles. But that still doesn't seem like a future-proof solution for the reasons above.

**Comment by gevgeny** [comment]
> The references may be necessary for building the package, but should be removed from distribution

No really. Actually the package's user will face with the typings as well (For example https://github.com/gevgeny/angular2-highcharts/blob/master/dist/ChartEvent.d.ts#L3) and another compile error will appear in this case: `error TS2304: Cannot find name 'HighchartsChartObject'.`
