### ISSUE TITLE
doesn' work with angular cli

### ISSUE THREAD

**Issue by lastnod** [gevgeny/angular2-highcharts#62]
doesn' work with angular cli

![image](https://cloud.githubusercontent.com/assets/8791187/18492751/3870fd1c-7a0d-11e6-85c7-b5de5890faa2.png)

![image](https://cloud.githubusercontent.com/assets/8791187/18492757/47ac9ed0-7a0d-11e6-9ee7-ea5d107f8492.png)

**Comment by ofadown** [comment]
not found doesnt mean it doesnt work; check your imports

**Comment by fank** [comment]
Should be fixed with the new version 0.3.0

**Comment by BasLee** [comment]
When will version 0.3.0 be released on NPM? :) https://www.npmjs.com/package/angular2-highcharts

**Comment by fank** [comment]
https://github.com/gevgeny/angular2-highcharts/pull/55#issuecomment-249527266
