### ISSUE TITLE
Support for Angular 2.0 Final Release

### ISSUE THREAD

**Issue by andvasp** [gevgeny/angular2-highcharts#64]
Can be provided  support for support for Angular 2.0 Final Release?

Thanks in advance!

**Comment by ravipunjwani** [comment]
+1

**Comment by david-lehmann** [comment]
+1

**Comment by Kianian** [comment]
+1

**Comment by buyology** [comment]
+1

**Comment by 14Muhammad** [comment]
When angular2-highcharts will be ready for Angular 2.0.0 final version ?

**Comment by singhjusraj** [comment]
+1

**Comment by peterkitonga** [comment]
+1

**Comment by lief480** [comment]
+1

**Comment by arjenbrandenburgh** [comment]
+1

**Comment by vapao** [comment]
+1

**Comment by BenoitFroment** [comment]
We are impatient.

**Comment by istiti** [comment]
How can I update ng2-hightchart working with angular2 final release? because I follow installation in readme this with Basic Usage and I get "Unexpected directive 'ChartComponent' imported by the module 'AppModule'"

**Comment by mshirishkumar** [comment]
need it very urgent.

**Comment by elvisbegovic** [comment]
@all my friends i'm confused, what do you mean by support angular 2 final, I'm using final with  this component and it works ...

**Comment by ravipunjwani** [comment]
@istiti , can you please share the version you are using for angular2 and highcharts? I doubt it works with all latest versions

**Comment by Kianian** [comment]
@ravipunjwani 
https://github.com/gevgeny/angular2-highcharts/pull/55#issuecomment-249392002

**Comment by fank** [comment]
Done see [v0.3.0](https://github.com/gevgeny/angular2-highcharts/releases/tag/v0.3.0)
