### ISSUE TITLE
version 0.3.0 not available on npm

### ISSUE THREAD

**Issue by scandinave** [gevgeny/angular2-highcharts#67]
Hi,
When i make `npm install angular-highcharts` the version download is 0.2.1.  This version does not work with Angular 2 because directive attribut is not available in @Component

Can you push it to npm please?

P.S : Great works anymore

**Comment by gevgeny** [comment]
See last comment here https://github.com/gevgeny/angular2-highcharts/pull/55

**Comment by scandinave** [comment]
Ok nice :)

**Comment by gevgeny** [comment]
published `angular2-highcharts@0.3.1`
https://github.com/gevgeny/angular2-highcharts/releases/tag/v0.3.1
