### ISSUE TITLE
typings problem duplicate identifier

### ISSUE THREAD

**Issue by marko033** [gevgeny/angular2-highcharts#74]
Hi, I have a problem.
I use angular-cli and final angluar 2.0.0 and I install angular2-highcharts.
I get error:
`\node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:3:13 
Duplicate identifier 'PropertyKey'
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:7:4 
All declarations of 'value' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:245:4 
All declarations of 'EPSILON' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:280:4 
All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:287:4 
All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:343:4 
All declarations of 'flags' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:495:4 
All declarations of 'prototype' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:558:4 
All declarations of 'size' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:567:4 
All declarations of 'prototype' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:578:4 
All declarations of 'size' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:587:4 
All declarations of 'prototype' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:602:4 
All declarations of 'prototype' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\es6-shim\index.d.ts:616:4 
All declarations of 'prototype' must have identical modifiers.
node_modules\angular2-highcharts\typings\globals\jasmine\index.d.ts:67:8 
Duplicate number index signature.
node_modules\angular2-highcharts\typings\globals\jasmine\index.d.ts:121:8 
Duplicate string index signature.
node_modules\typescript\lib\lib.es2015.core.d.ts:17:13 
Duplicate identifier 'PropertyKey'.`

**Comment by gevgeny** [comment]
Probably dup of https://github.com/gevgeny/angular2-highcharts/issues/69. Could you try to current master branch version and check whether it works ?

**Comment by tmfcosta** [comment]
Using the master branch that error is fixed, but in the browser I get this problem:

Error loading https://cdn.rawgit.com/gevgeny/angular2-highcharts/v0.3.0/dist as "angular2-highcharts" from http://localhost:3000/app/app.module.js

Anyone knows why ?

**Comment by ajitatif** [comment]
I had the very same issue until I cloned master branch and changed 'angular2-highcharts' dependency to local directory worked out for me too.

Yet I had to add:
`
..
 map: {
      'angular2-highcharts': 'npm:angular2-highcharts',
      'highcharts/highstock.src':   'https://cdn.rawgit.com/highcharts/highcharts-dist/v4.2.1/highstock.js'
},
packages {
...
      'angular2-highcharts': {
        main: './index.js',
        defaultExtension: 'js'
      },
...
`
to systemjs.config.json.

The issue is likely because of typings configs; since my project's typings is not "stock" (below)
`{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160725163759",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:dt/node#6.0.0+20160909174046",
    "jquery": "registry:dt/jquery#1.10.0+20160704162008",
    "jquery.simplemodal": "registry:dt/jquery.simplemodal#0.0.0+20160317120654"
  }
}`

**Comment by marko033** [comment]
Sorry I dont now how use master branch version?
Can you help me?
Download zip and replace files in node_modules\angular2-highcharts with files in zip?

**Comment by gevgeny** [comment]
Looks at this example https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by marko033** [comment]
sorry didn't help

**Comment by ajitatif** [comment]
@marko033, you can simply put below in dependencies section of your package.json:

`"angular2-highcharts": "https://github.com/gevgeny/angular2-highcharts",`

afterwards clean your `node_modules` directory by deleting it and run `npm install` again. this will acquire the library from github master branch's latest commit.

along with the snippets I wrote above in systemjs.config.js, this worked out for me

**Comment by marko033** [comment]
@ajitatif thx it works, but now i have error:

> EXCEPTION: Error in ./ChartComponent class ChartComponent - inline template:42:33 caused by: Highcharts error #17: www.highcharts.com/errors/17

**Comment by marko033** [comment]
How can i add highcharts-more.js I try add in angular-cli.json 

```
"scripts": [
"../node_modules/angular2-highcharts/dist/highcharts-more.js"  
],
```

but I get error 

> Uncaught ReferenceError: Highcharts is not defined

**Comment by ajitatif** [comment]
the highcharts error seems to be because of your chart options. try a simpler one like `chart: {
                type: 'line'
            },
            title: { text: 'Test Chart' },
            series: [
                { data: [ 25, 27.5, 33, 20, 22, 25, 27, 31, 30, 30, 34, 29.7 ] }
            ]
`
about highcharts more, i have absolutely no idea.

i hope this will help you out; otherwise i fear this thread will end up being off-topic
