### ISSUE TITLE
add highcharts-more.js

### ISSUE THREAD

**Issue by marko033** [gevgeny/angular2-highcharts#77]
How can i add highcharts-more.js I try add in angular-cli.json 

```
"scripts": [
"../node_modules/angular2-highcharts/dist/highcharts-more.js"  
],
```

but I get error 

> Uncaught ReferenceError: Highcharts is not defined

**Comment by gevgeny** [comment]
See the highcharts modules section of readme. Also issue was resolved here https://github.com/gevgeny/angular2-highcharts/issues/28
