### ISSUE TITLE
not working with angular2-highcharts and systemjs

### ISSUE THREAD

**Issue by anshumanpatil** [gevgeny/angular2-highcharts#78]
Error: @http://localhost:8000/node_modules/angular2-highcharts/dist/Highcharts.js:2:18
    @http://localhost:8000/node_modules/angular2-highcharts/dist/Highcharts.js:1:31
    @http://localhost:8000/node_modules/angular2-highcharts/dist/Highcharts.js:1:2
    @http://localhost:8000/node_modules/angular2-highcharts/dist/HighchartsService.js:2:20
    @http://localhost:8000/node_modules/angular2-highcharts/dist/HighchartsService.js:1:31
    @http://localhost:8000/node_modules/angular2-highcharts/dist/HighchartsService.js:1:2
    @http://localhost:8000/node_modules/angular2-highcharts/dist/ChartComponent.js:6:27
    @http://localhost:8000/node_modules/angular2-highcharts/dist/ChartComponent.js:1:31
    @http://localhost:8000/node_modules/angular2-highcharts/dist/ChartComponent.js:1:2
    @http://localhost:8000/node_modules/angular2-highcharts/dist/index.js:3:24
    @http://localhost:8000/node_modules/angular2-highcharts/dist/index.js:1:31
    @http://localhost:8000/node_modules/angular2-highcharts/dist/index.js:1:2
    ZoneDelegate.prototype.invoke@http://localhost:8000/node_modules/zone.js/dist/zone.js:203:19
    Zone.prototype.run@http://localhost:8000/node_modules/zone.js/dist/zone.js:96:24
    scheduleResolveOrReject/<@http://localhost:8000/node_modules/zone.js/dist/zone.js:462:52
    ZoneDelegate.prototype.invokeTask@http://localhost:8000/node_modules/zone.js/dist/zone.js:236:23
    Zone.prototype.runTask@http://localhost:8000/node_modules/zone.js/dist/zone.js:136:28
    drainMicroTaskQueue@http://localhost:8000/node_modules/zone.js/dist/zone.js:368:25
    ZoneTask/this.invoke@http://localhost:8000/node_modules/zone.js/dist/zone.js:308:25

```
Evaluating http://localhost:8000/highcharts/highstock.src
Evaluating http://localhost:8000/node_modules/angular2-highcharts/dist/Highcharts.js
Evaluating http://localhost:8000/node_modules/angular2-highcharts/dist/HighchartsService.js
Evaluating http://localhost:8000/node_modules/angular2-highcharts/dist/ChartComponent.js
Evaluating http://localhost:8000/node_modules/angular2-highcharts/dist/index.js
Error loading http://localhost:8000/app/main.js
```

http://localhost:8000/node_modules/systemjs/dist/system.src.js
Line 123

SystemJS Config -
'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api'
          &
'angular2-highcharts': {
    main: './index.js',
    defaultExtension: 'js'
  }

import { ChartModule } from 'angular2-highcharts';
@NgModule({
  imports:      [BrowserModule,FormsModule,routing,HttpModule,ChartModule],
  declarations: [AppComponent],
  bootstrap:    [AppComponent]
})
export class AppModule { }  

and in html
<chart [options]="options"></chart>

**Comment by gevgeny** [comment]
From the stack trace it is not clear what kind of problem you have. Could you provide more details ?

**Comment by anshumanpatil** [comment]
@gevgeny  you can see whole sample on github here [https://github.com/anshumanpatil/angular2error.git](https://github.com/anshumanpatil/angular2error.git)

**Comment by anshumanpatil** [comment]
and thanks in advance for help
@gevgeny

**Comment by gevgeny** [comment]
Would be great to look at working live demo forked of one of the demos

**Comment by anshumanpatil** [comment]
@gevgeny  have you tried above git project ? I tried lot much but it fails to run :(
