### ISSUE TITLE
Error including in an Ionic2 project

### ISSUE THREAD

**Issue by SudharsanSukumar** [gevgeny/angular2-highcharts#79]
Hi,

I'm trying to include angular2-highcharts in my Ionic2 Project. It was working previously until Ionic2 upgraded from Angular2 RC4 (before ngModule) to Angular 2.0 (after ngModule). I started with a new Ionic2 project and have been moving files over.

**Note**
Not sure if relevant, but Ionic2 switched to rollup to build everything. I think that's different than what the Angular2 CLI uses to build.

**Errors**
The following errors appear when importing ChartModule to the App Module 

> [17:05:20]  typescript compilation started ...
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'.
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(7,5): error TS2687: All declarations of 'value' must have identical modifiers.
> node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(245,5): error TS2687: All declarations of 'EPSILON' must have identical modifiers.
> node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(280,5): error TS2687: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(287,5): error TS2687: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(343,5): error TS2687: All declarations of 'flags' must have identical modifiers.
> node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(495,5): error TS2687: All declarations of 'prototype' must have identical modifiers.
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(558,5): error TS2687: All declarations of 'size' must have identical modifiers.
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(567,5): error TS2687: All declarations of 'prototype' must have identical modifiers.
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(578,5): error TS2687: All declarations of 'size' must have identical modifiers.
> node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(587,5): error TS2687: All declarations of 'prototype' must have identical modifiers.
> [17:05:23]  node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(602,5): error TS2687: All declarations of 'prototype' must have identical modifiers.
> node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(616,5): error TS2687: All declarations of 'prototype' must have identical modifiers.
> [17:05:23]  node_modules/typescript/lib/lib.es2015.core.d.ts(17,14): error TS2300: Duplicate identifier 'PropertyKey'.

Further, if I then include ChartModule as an import in the appModule (like in your latest example), I get this error:

> typescript compilation started ...
> [17:10:31]  bundle dev update started ...
> [17:10:32]  typescript compilation finished in 3.07 s
> [17:10:35]  Error: Module C:\cygwin64\home\removed\node_modules\angular2-highcharts\index.js does not export ChartModule (imported by C:\cygwin64\homeremoved.tmp\app\app.module.js)
>     at Module.trace (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:7677:29)
>     at ModuleScope.findDeclaration (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:7300:22)
>     at Scope.findDeclaration (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5351:39)
>     at Identifier.bind (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:6489:29)
>     at C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:50
>     at ArrayExpression.eachChild (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5165:19)
>     at ArrayExpression.bind (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:7)
>     at C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:50
>     at Node.eachChild (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5168:5)
>     at Node.bind (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:7)

**Package.json:**

> {
>   "name": "removed",
>   "author": "removed",
>   "homepage": "removed",
>   "main": "electron.js",
>   "private": true,
>   "scripts": {
>     "build": "ionic-app-scripts build",
>     "watch": "ionic-app-scripts watch",
>     "serve:before": "watch",
>     "emulate:before": "build",
>     "deploy:before": "build",
>     "build:before": "build",
>     "run:before": "build"
>   },
>   "dependencies": {
>     "@ionic/storage": "1.0.3",
>     "angular2-highcharts": "^0.3.2",
>     "electron": "^1.4.1",
>     "ionic-angular": "^2.0.0-rc.0",
>     "ionic-native": "^2.0.3",
>     "ionicons": "^3.0.0"
>   },
>   "devDependencies": {
>     "@ionic/app-scripts": "^0.0.23",
>     "typescript": "^2.0.3"
>   },
>   "description": "removed",
>   "cordovaPlugins": [
>     "cordova-plugin-device",
>     "cordova-plugin-console",
>     "cordova-plugin-whitelist",
>     "cordova-plugin-splashscreen",
>     "cordova-plugin-statusbar",
>     "ionic-plugin-keyboard"
>   ],
>   "cordovaPlatforms": []
> }

**Comment by fank** [comment]
This is fixed, but still not released.
@gevgeny we should publish the new version soon

**Comment by SudharsanSukumar** [comment]
Awesome :D glad to hear it!

**Comment by gevgeny** [comment]
published angular2-highcharts@0.3.3

**Comment by SudharsanSukumar** [comment]
Hey again!

I updated to 0.3.3 (deleted from angular modules, updated package.json and npm install again) and I'm getting errors (but different ones now :D)

The error only comes when including ChartModule in the appModule imports array. Just importing ChartModule from 'angular2-highcharts' does not give any errors.

Here they are:

> [00:54:48]  bundle dev started ...
> [00:54:54]  Error: Module C:\cygwin64\home\removed\node_modules\angular2-highcharts\index.js does not export ChartModule (imported by C:\cygwin64\home\removed.tmp\app\app.module.js)
>     at Module.trace (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:7677:29)
>     at ModuleScope.findDeclaration (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:7300:22)
>     at Scope.findDeclaration (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5351:39)
>     at Identifier.bind (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:6489:29)
>     at C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:50
>     at ArrayExpression.eachChild (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5165:19)
>     at ArrayExpression.bind (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:7)
>     at C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:50
>     at Node.eachChild (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5168:5)
>     at Node.bind (C:\cygwin64\home\removed\node_modules\rollup\dist\rollup.js:5151:7)
> 
> [00:54:54]  sass started ...
> [00:54:55]  sass finished in 1.30 s
> [00:54:55]  build dev finished in 12.17 s
> [00:54:55]  watch ready in 12.21 s

Thanks again for your help!

**Comment by gevgeny** [comment]
Would be great if somebody who is familiar with ionic2 tryes to investigate the problem ;)

**Comment by SudharsanSukumar** [comment]
[I made a post on the Ionic2 forums](https://forum.ionicframework.com/t/error-importing-angular2-highcharts-v0-3-3/65315). They're getting flooded with issues since RC0 just came out on Thursday so we'll see if anyone responds :P.

-Dharsan

**Comment by gevgeny** [comment]
thanks!

**Comment by paatrick** [comment]
I have the same problem: /

**Comment by SudharsanSukumar** [comment]
Are you using Ionic2 as well? Or Angular2?

**Comment by paatrick** [comment]
I using Ionic2, any solution envisaged?

**Comment by codedumper** [comment]
I've got the same issue. It's ionic related. 
Got the same issue with ionic 2.0 rc0 with angular2-highcharts and ng2-highcharts.
It works fine without ionic on angular 2.0.1

**Comment by kevin1992** [comment]
I have the same problem on ionic 2.0 any solution?

**Comment by SudharsanSukumar** [comment]
Looks like any Ionic2 and rollup error. [Here's the open issue](https://github.com/driftyco/ionic/issues/8322).

-Dharsan

**Comment by SudharsanSukumar** [comment]
Well I got it to work!

An important note is that this is a workaround for Ionic2 RC0 so future people shouldn't have to do this.

1: Open node_modules/@ionic/app-scripts/config/rollup.config.js

2: Change so it looks like (add stuff to commonjs call):

```
var ngTemplate = require('../dist/plugins/ng-template').ngTemplate;
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');

// https://github.com/rollup/rollup/wiki/JavaScript-API

module.exports = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: './.tmp/app/main.dev.js',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    ngTemplate(),
    commonjs({
      namedExports: { 'node_modules/angular2-highcharts/index.js':['ChartModule']}
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    })
  ]

};

```
1. Open the node module you declare the chart component in (AppModule in the example). And import {ChartModule} from 'angular2-highcharts' and then add ChartModule to the NgModel imports array:

```
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { MyChartComponent } from 'path/to/chart/component';
import { ChartModule } from 'angular2-highcharts';

@NgModule({
  declarations: [
    MyApp,
    MyChartComponent
  ],
  imports: [
    ChartModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    MyChartComponent //Not sure if this needs to be here but I think it might.
  ],
  providers: []
})
export class AppModule { }
```

Hope that helps!
Dharsan

**Comment by fank** [comment]
@gevgeny i've got the same problem in angular2 when we switch our project to rollup with AoT, it looks like we need to change the way how we declare the NgModule.

**Comment by macdosi** [comment]
Does @SudharsanSukumar  answer still relevant ? I have the same issue with ionic app scripts 0.0.45

**Comment by SudharsanSukumar** [comment]
I don't think it's an issue now that ionic switched to Webpack by default. If you're using Rollup still then it probably still needs to be done. 

-Dharsan

**Comment by macdosi** [comment]
I use app scripts 0.0.45 , so it's webpack and I'm facing the same problem . with ionic rc3 .
But I see the "node_modules/@ionic/app-scripts/config/rollup.config.js" file . how can it be if ionic moved to webpack ?

**Comment by MarkySparky** [comment]
They still support rollup of that is what you were using and prefer to use, so the configs are still there
