### ISSUE TITLE
Size: (width and height)

### ISSUE THREAD

**Issue by demiro** [gevgeny/angular2-highcharts#82]
How do I set the width of the chart?

`<chart         width="150"         type="StockChart"       [options]="chartOptions"        (load)="load"   ></chart>`

this doesn't work

```
chartOptions = {
            width: 150,
...
}
```

doesn't work either

the only thing that changes the width from default's 600 is setting it directly to the component (or via the style or class)

if I do 

`<chart         class="col-xs-2"        type="StockChart"       [options]="chartOptions"        (load)="load"   ></chart>`

where col-xs-2 is a bootstrap's class
or

`<chart         style="width:150px"         type="StockChart"       [options]="chartOptions"        (load)="load"   ></chart>`

then it works...

I would like to set the chart's size (width/height) dynamically if possible, like so:

`<chart         [width]="chartWidth"        type="StockChart"       [options]="chartOptions"        (load)="load"   ></chart>`

so that when chartWidth changes the chart is redrawn

**Comment by gevgeny** [comment]
> I would like to set the chart's size (width/height) dynamically if possible

Unfortunately it is not possible. See FAQ in the readme

**Comment by demiro** [comment]
Well, OK... but how do I set the width in the first place? 
let's say to 100% of the parent element?

**Comment by gevgeny** [comment]
See demos. AFAIK the first one is flexible and has parent size

**Comment by demiro** [comment]
the problem is if I do
`<chart style="width: 100%;"  ....>`

it get's relative to the document and not the parent :/

**Comment by gevgeny** [comment]
could you plz provide live demo ?

**Comment by demiro** [comment]
sorry I can't... closed corporate network... but I guess is relative to "renderTo" property...
I am getting weird behavior... specially if the chart is on a hidden panel (tab)... when I open the tab the width is different... to the one I access first (chart tab open)...  is there an option to redraw the chart on event? or how do I set renderTo in angular? what would be the reference?

**Comment by gevgeny** [comment]
you can make simple example forking one of the demos

**Comment by aderbas** [comment]
I made an example, and the chart does not adjust the parent's size for me too.
https://github.com/aderbas/teste-app

![chart-size](https://cloud.githubusercontent.com/assets/12519019/19859297/85e985f2-9f63-11e6-9fd7-af1da1e4e6c7.png)

**Comment by aderbas** [comment]
In my css I force 100% width and solve it

```
  chart{
    width: 100% !important;
  }
```

**Comment by born2net** [comment]
same issue ... can't make it 100% responsive.
And, if I do:
```
chart{
    width: 100% !important;
  }
```
it will take the entire width of the screen :(

**Comment by windmaomao** [comment]
set display: block to the chart as in the online example.

**Comment by sachinmishra007** [comment]
The inner css classes of the chart can be used.<br/>
the highcharts basically contains **highcharts-container** and **highcharts -root** classes.<br/>So In case if you would like to adjust the chart size I would suggest to use.


.highcharts-root{<br/>
         width:500px !important<br/>
}

I hope this will help you !!

**Comment by shafaqkazmi** [comment]
CSS doesn't work for me. Any other solution?

**Comment by Malaratgithub** [comment]
adding  display: block to style, works for me. Thanks windmaomao

**Comment by AbelValdez** [comment]
@shafaqkazmi  try using a parent element with the size in this case is boostrap class

```
<div class="col-lg-5" style="border: solid 1px;">
<chart [options]="options" style="display:block; width: 100% !important;"></chart>
</div>
```

**Comment by WinfredMa** [comment]
Size can be setted in chart options.
chart: {
            inverted: true,
            marginLeft: 135,
            type: 'bullet',
            width: 800,
            height: 200
}
