### ISSUE TITLE
how to use solidgauge chart

### ISSUE THREAD

**Issue by BenoitFroment** [gevgeny/angular2-highcharts#87]
Hello,

Like here : http://stackoverflow.com/questions/38999362/include-additional-highcharts-source-data-in-angular2-app

i need to use solidgauge with angular-cli webpack version, could u provide me an example please ?

**Comment by unaor** [comment]
were you able to resolve this?

**Comment by BenoitFroment** [comment]
no sry

**Comment by vaseapopa** [comment]
Does anyone have any update on this? I'm able to add the gauge chart as written in the stackoverflow issue linked above, but we're using an angular cli workflow in our project and we'd also like to have gauges integrated the same way. CLI version is 1.0.0-beta.24

**Comment by saiidabs** [comment]
in your @NgModule imports have 

	ChartModule.forRoot(require('highcharts')
			,require('highcharts/highcharts-more')
			,require('highcharts/modules/solid-gauge')),

in your component.ts file just 
import { ChartModule  } from 'angular2-highcharts'; 

in the contructor this.options = {
        chart: {
            type: 'solidgauge'
        },

        title: null,

        pane: {
            center: ['50%', '85%'],
            size: '140%',
            startAngle: -90,
            endAngle: 90,
            background: {
                backgroundColor:  '#EEE',
                innerRadius: '60%',
                outerRadius: '100%',
                shape: 'arc'
            }
        },

        tooltip: {
            enabled: false
        },

        // the value axis
        yAxis: {
            stops: [
                [0.1, '#55BF3B'], // green
                [0.5, '#DDDF0D'], // yellow
                [0.9, '#DF5353'] // red
            ],
            lineWidth: 0,
            minorTickInterval: null,
            tickAmount: 2,
            title: {
                y: -70,
                text: 'Speed'
            },
            labels: {
                y: 16
            },
            min: 0,
            max: 100
        },

        plotOptions: {
            solidgauge: {
                dataLabels: {
                    y: 5,
                    borderWidth: 0,
                    useHTML: true
                }
            }
        },

        credits: {
            enabled: false
        },

        series: [{
            name: 'Speed',
            data: [80],
            dataLabels: {
               format: '<div style="text-align:center"><span style="font-size:25px;color: black' +
                        '">{y}</span><br/>' +
                       '<span style="font-size:12px;color:silver">km/h</span></div>'
            },
            tooltip: {
                valueSuffix: ' km/h'
            }
        }]

    };

in your html 
<chart [options]="options"></chart>

**Comment by beabri** [comment]
I all, I have the same issue, but with the Chart Type "gauge". I don't use angular-cli neither webpack, only using systemjs.config.js.

Here my app.module.ts:

```
import { ChartModule } from 'angular2-highcharts';

@NgModule({
  imports: [
    ChartModule.forRoot('highcharts'),
    ChartModule.forRoot('highcharts/highcharts-more'),
    ChartModule.forRoot('highcharts/modules/solid-gauge'),
  ]
})
export class AppModule {
}
```


And my sistemjs.config.js:

```
        packages: {
            highcharts: {
                main: './highcharts.js',
                defaultExtension: 'js'
            },
            'angular2-highcharts': {
                main: './index.js',
                defaultExtension: 'js'
            }            
        },
     resolve: {
      alias: {
        // NOTE: You should set 'highcharts/highcharts.src.js'
        // if you are not going to use <chart type="StockChart"
        highcharts$: "highcharts/highcharts-more.src.js"
      }

```

What am I missing?

**Comment by athiraskumar** [comment]
I get the error Property 'forRoot' does not exist on type 'typeof ChartModule'

**Comment by pdbaotrung** [comment]
@saiidabs Thanks a lot for your example
