### ISSUE TITLE
Calling HighchartsChartObject.redraw function doesn't work.

### ISSUE THREAD

**Issue by 4sur3** [gevgeny/angular2-highcharts#9]
Hi Guys

In my case I'm using Angular2. When I try to change the chart.type of my chart ('line', 'column',etc) it doesn't work. 

Is it necessary to do something else than calling the redraw or is a problem?. 

Thanks in advance,

J

**Comment by gevgeny** [comment]
I think it is more question about Highcharts rather than angular2-highcharts. Look at this example http://jsfiddle.net/5wzm6ncu/.

**Comment by 4sur3** [comment]
You are right. Thanks.
