### ISSUE TITLE
 not sizing correctly until window resize

### ISSUE THREAD

**Issue by capcar** [gevgeny/angular2-highcharts#90]
I have one class:

```
export class Widget {
  options: Array<NgGridItem>;
  content: Array<Ng2Highcharts>;
}
```

and in html:

```
 <div class="col-xl-6 grid-item" >
            <div *ngFor="let box of widgetsList" [(ngGridItem)]=" box.options.config" [ng2-highcharts]=" box.content" > 
           </div>
   < /div>
```

widgetsList is one array of Widget
I obtain options and content from json file.
Charts have not sizing correctly until window resize. Must I use reflow?? How I must use it?

**Comment by gevgeny** [comment]
this is not ng2-highcharts repository

**Comment by ghost** [comment]
@capcar , did you ever find a solution to your resizing issue? I am having the same problem with the ng2-highcharts repository and cannot find a solution for the life of me.

**Comment by capcar** [comment]
no, I don't find a solution, and you?
