### ISSUE TITLE
Highcharts modules

### ISSUE THREAD

**Issue by kschio** [gevgeny/angular2-highcharts#91]
Hi Eugene,

thanks for the great wrapper!

The only thing missing are the modules which can be super helpful such as `data` `('highcharts/modules/data')` for parsing CSV files for example.

I solved it by importing the needed modules but it would be great if they would be somehow configurable or already available.

Is there any reason the highcharts modules are not imported by default?

Cheers
Kevin

**Comment by gevgeny** [comment]
Hi Kevin. How do you import them now ?

**Comment by kschio** [comment]
Hi Eugene,

as I had no time to do it properly yet, I just put the following in `dist/Highcharts.js`:

```
"use strict";
var Highcharts = require('highcharts/highstock.src');
require('highcharts/modules/data')(Highcharts);
exports.Highcharts = Highcharts;
```

It does what I need but is not the best way I suppose. Upgraded to Highcharts 5 as well and had no problems so far :)

If I find the time I will set up a PR with a better solution.

**Comment by gevgeny** [comment]
See the examples for new v0.4.0 version https://github.com/gevgeny/angular2-highcharts#installation
