### ISSUE TITLE
Error running Highmaps demo

### ISSUE THREAD

**Issue by sriramcms** [gevgeny/angular2-highcharts#92]
thanks for the great wrapper!

I got the Basic charts and Stockchart working with Angular 2.  Run into problems with Highmaps

I am trying to get this below Highmaps working with Angular 2 - 
http://plnkr.co/edit/AmDfKwhRhshFn3CPprkk?p=preview
I see this in the above --  var ngVer = '@2.0.0-rc.1'; // lock in the angular package version; do not let it float to current!

I keep getting issues like below.

---

ERROR in [default] /home/mapr/bo_highcharts/src/main.ts:4:45
Cannot find module 'highcharts/modules/map'.

ERROR in [default] /home/mapr/bo_highcharts/src/main.ts:10:4
Argument of type '{ selector: string; directives: any[][]; styles: string[]; template: string; }' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

Am i missing something ?

**Comment by gevgeny** [comment]
Hm, the demo runs fine for me

**Comment by sriramcms** [comment]
Thanks  Eugene. 

Summary 
1.  It WORKED after i copied ur plunker exactly as is.    I ignored the below errors and still it worked.   This is standalone test. 
2. Im now trying to embed this within the https://github.com/akveo/ng2-admin and running into issues like   "error_handler.js:46 EXCEPTION: Uncaught (in promise): TypeError: map_1.default is not a function"

****************\* Errors for point 1 above (ignorable ?)
ERROR in [default] /home/mapr/test_highmaps_2rc1/src/app/main.ts:1:9
Module '"/home/mapr/test_highmaps_2rc1/node_modules/@angular/platform-browser-dynamic/index"' has no exported member 'bootstrap'.

ERROR in [default] /home/mapr/test_highmaps_2rc1/src/app/main.ts:4:45
Cannot find module 'highcharts/modules/map'.

ERROR in [default] /home/mapr/test_highmaps_2rc1/src/app/main.ts:10:4
Argument of type '{ selector: string; directives: any[][]; styles: string[]; template: string; }' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

**Comment by gevgeny** [comment]
See the installation step in the readme to know how to plug highcharts modules with new version

**Comment by sriramcms** [comment]
Thanks. The installation was useful.  I was able to plug the samples into a Angular2-Typescript-Gulp example.   Tested basic , maps and stock charts.  

Only thing i noticed was that  i had to add the below in  angular2-highcharts/dist/index.d.ts or else i keep getting CHART_DIRECTIVES not defined
"export declare const CHART_DIRECTIVES: any[];  "
