### ISSUE TITLE
global options not working

### ISSUE THREAD

**Issue by lesliesu** [gevgeny/angular2-highcharts#98]
I need to set highcharts global option useUTC to false; I am doing as follows, but have no luck to make it works yet.

`let Highcharts = require('../../../../node_modules/highcharts');`

`const globalChartOptions: HighchartsGlobalOptions = {
`  global: {`
`    useUTC: false,`
`  }`
`};`

`static createDatetimeXAxisLineChartOption(): HighchartsOptions {`
`Highcharts.setOptions(globalChartOptions);`
`console.log(Highcharts.getOptions());`
`return  ...;`

I could learn from the console page that the globalChartOptions DOES change the value of Highcharts, but it seems like this global instance I set up is not the SAME one that has been used for drawing the chart.

**Comment by gevgeny** [comment]
Yea, probably you are using different instances of Highcharts. Now you can chose whether to use highcharts or highstock.  Look at the examples from readme 
webpack - https://github.com/gevgeny/angular2-webpack-starter-and-angular2-highcharts/commit/fffbebfd7974f808242dbbb8eccdfc108dde72cf
SystemJS - https://github.com/gevgeny/angular2-quickstart-and-angular2-highcharts/commit/5021ff2b7f615a5b566b4bab0faf70991f5a53db

**Comment by cozyazure** [comment]
@gevgeny , I think I face the same issue too. By default, if I were to use 

```
import * as HighCharts from 'highcharts';
```

the highcharts will load the typing files first, from `index.d.ts`, instead from the `highcharts` node modules. To explicitly get the highcharts static members, I need to do this 

```
import {Highcharts} from 'angular2-highcharts/dist/HighChartsWrapper'
```

I think there is a conflict with same module name somewhere.

@lesliesu , you can refer to the [README.md](https://github.com/cozyazure/angular2-highcharts#styling-highcharts-and-globaloptions) of my fork and see if it helps you. Basically you should not be confused with the typings and the static member

**Comment by gevgeny** [comment]
@cozyazure I have not added any mention of the `HighChartsWrapper` to the readme intentionally because it is planned to be private. Since v0.4.0 you need to use native highcharts API just like it used in the examples above.

**Comment by lesliesu** [comment]
Thank you @gevgeny and @cozyazure ,  The issue disappeared after I referred @gevgeny's suggestion, and upgraded angular2-highcharts to 0.4.1.

Sorry for my late reply.
